import assert from "node:assert/strict";
import test from "node:test";
import { parseManualCommonPlayOperationDefinition, resolveCommonPlayEntryPointOperations } from "../../src/domain/commonPlayOperationRuntime";
import { runtimeState, TEST_PROFILE } from "./rulesTestState";
function stateWithProne(){const state=runtimeState();state.clock.activeActorId="hero";state.clock.phase="action";state.combatants.hero.economy.movement=30;state.combatants.hero.economy.movementMaximum=30;state.effects.push({id:"effect.external.prone",sourceId:"external.unknown.prone-source",targetId:"hero",kind:"condition",conditionId:"prone",tags:[],expiry:{kind:"permanent"}});return state;}
function definition(id="external.unknown.family-i-stand"){return parseManualCommonPlayOperationDefinition({schemaVersion:"0.2-draft",id,entryPoints:[{id:"stand",invocation:"manual",operations:[{kind:"movement.stand",target:"actor"}]}]});}
test("portable movement.stand spends half effective speed and removes Prone atomically",()=>{const committed=resolveCommonPlayEntryPointOperations(TEST_PROFILE,stateWithProne(),definition(),{resolutionId:"stand-resolution",actorId:"hero",entryPointId:"stand"});assert.equal(committed.status,"committed");if(committed.status!=="committed")return;assert.equal(committed.state.combatants.hero.economy.movement,15);assert.equal(committed.state.effects.some((effect)=>effect.conditionId==="prone"&&effect.targetId==="hero"),false);assert.equal(committed.events.length,2);assert.match(committed.events[0].summary,/stands from Prone/);assert.ok(committed.events[0].stateChanges.some((change)=>change.kind==="economy"&&change.field==="movement"));assert.ok(committed.events[1].stateChanges.some((change)=>change.kind==="effect"&&change.effectId==="effect.external.prone"&&change.after===undefined));});
test("portable movement.stand rejects insufficient movement without partially removing Prone",()=>{const state=stateWithProne();state.combatants.hero.economy.movement=10;const rejected=resolveCommonPlayEntryPointOperations(TEST_PROFILE,state,definition(),{resolutionId:"stand-insufficient",actorId:"hero",entryPointId:"stand"});assert.equal(rejected.status,"rejected");assert.equal(state.combatants.hero.economy.movement,10);assert.equal(state.effects.some((effect)=>effect.conditionId==="prone"),true);});
test("portable movement.stand rejects zero effective speed without removing Prone",()=>{const state=stateWithProne();state.effects.push({id:"effect.external.grappled",sourceId:"external.unknown.grapple",sourceActorId:"enemy",targetId:"hero",kind:"condition",conditionId:"grappled",tags:[],expiry:{kind:"permanent"}});const rejected=resolveCommonPlayEntryPointOperations(TEST_PROFILE,state,definition(),{resolutionId:"stand-zero-speed",actorId:"hero",entryPointId:"stand"});assert.equal(rejected.status,"rejected");assert.equal(state.combatants.hero.economy.movement,30);assert.equal(state.effects.some((effect)=>effect.conditionId==="prone"),true);});
test("portable movement.stand semantics are invariant under external definition identity rename",()=>{const first=resolveCommonPlayEntryPointOperations(TEST_PROFILE,stateWithProne(),definition("external.first.stand"),{resolutionId:"stand-first",actorId:"hero",entryPointId:"stand"});const second=resolveCommonPlayEntryPointOperations(TEST_PROFILE,stateWithProne(),definition("unrelated.renamed.stand"),{resolutionId:"stand-second",actorId:"hero",entryPointId:"stand"});assert.equal(first.status,"committed");assert.equal(second.status,"committed");if(first.status!=="committed"||second.status!=="committed")return;assert.equal(first.state.combatants.hero.economy.movement,second.state.combatants.hero.economy.movement);assert.equal(first.state.effects.some((effect)=>effect.conditionId==="prone"),false);assert.equal(second.state.effects.some((effect)=>effect.conditionId==="prone"),false);});
