import type { SpellMechanicDefinition } from "./spellcasting";

export const SRD_521_SPELL_MECHANICS: Record<string, SpellMechanicDefinition> = {
  "dnd.srd521.spell.fire-bolt": {
    spellId: "dnd.srd521.spell.fire-bolt",
    baseLevel: 0,
    runtimeSupport: "combat-executable",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 120,
      minTargets: 1,
      maxTargets: 1,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      directTarget: true,
    },
    primary: {
      kind: "attack-damage",
      damageType: "fire",
      dice: { count: 1, sides: 10, cantripScaling: true },
    },
    executionScope: "Creature-target combat resolution. The separate flammable-object rider is outside this execution envelope.",
  },
  "dnd.srd521.spell.sacred-flame": {
    spellId: "dnd.srd521.spell.sacred-flame",
    baseLevel: 0,
    runtimeSupport: "combat-executable",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 60,
      minTargets: 1,
      maxTargets: 1,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      requiresSight: true,
      directTarget: true,
    },
    primary: {
      kind: "save-damage",
      saveAbility: "dex",
      damageType: "radiant",
      dice: { count: 1, sides: 8, cantripScaling: true },
      successDamage: "none",
      ignoresCoverForSave: true,
    },
  },
  "dnd.srd521.spell.healing-word": {
    spellId: "dnd.srd521.spell.healing-word",
    baseLevel: 1,
    runtimeSupport: "combat-executable",
    castingEconomy: "bonus-action",
    targeting: {
      kind: "creature",
      rangeFeet: 60,
      minTargets: 1,
      maxTargets: 1,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      requiresSight: true,
      directTarget: true,
    },
    primary: {
      kind: "healing",
      dice: {
        count: 2,
        sides: 4,
        addSpellcastingModifier: true,
        dicePerSlotAboveBase: 2,
      },
    },
  },
  "dnd.srd521.spell.cure-wounds": {
    spellId: "dnd.srd521.spell.cure-wounds",
    baseLevel: 1,
    runtimeSupport: "combat-executable",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 5,
      minTargets: 1,
      maxTargets: 1,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      directTarget: true,
    },
    primary: {
      kind: "healing",
      dice: {
        count: 2,
        sides: 8,
        addSpellcastingModifier: true,
        dicePerSlotAboveBase: 2,
      },
    },
  },
  "dnd.srd521.spell.burning-hands": {
    spellId: "dnd.srd521.spell.burning-hands",
    baseLevel: 1,
    runtimeSupport: "combat-executable",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 15,
      minTargets: 1,
      maxTargets: 64,
      allowedRelations: ["ally", "enemy", "neutral"],
      directTarget: false,
    },
    primary: {
      kind: "save-damage",
      saveAbility: "dex",
      damageType: "fire",
      dice: { count: 3, sides: 6, dicePerSlotAboveBase: 1 },
      successDamage: "half",
    },
    executionScope: "Creature damage in the authoritative 15-foot Cone. Environmental ignition is outside this execution envelope.",
  },
  "dnd.srd521.spell.magic-missile": {
    spellId: "dnd.srd521.spell.magic-missile",
    baseLevel: 1,
    runtimeSupport: "combat-executable",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 120,
      minTargets: 1,
      maxTargets: 3,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      requiresSight: true,
      directTarget: true,
    },
    primary: {
      kind: "automatic-projectiles",
      damageType: "force",
      projectileDice: { sides: 4, flat: 1 },
      baseProjectiles: 3,
      projectilesPerSlotAboveBase: 1,
    },
    unsupportedInteractions: ["A target protected by the Shield spell needs the Shield spell's explicit Magic Missile immunity effect in runtime state."],
    executionScope: "Exact projectile allocation/damage when no unmaterialized spell-specific immunity overrides the generic damage pipeline.",
  },
  "dnd.srd521.spell.vicious-mockery": {
    spellId: "dnd.srd521.spell.vicious-mockery",
    baseLevel: 0,
    runtimeSupport: "partial",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 60,
      minTargets: 1,
      maxTargets: 1,
      allowedRelations: ["self", "ally", "enemy", "neutral"],
      requiresSight: true,
      directTarget: true,
    },
    primary: {
      kind: "save-damage",
      saveAbility: "wis",
      damageType: "psychic",
      dice: { count: 1, sides: 6, cantripScaling: true },
      successDamage: "none",
    },
    unsupportedInteractions: ["The failed-save rider that penalizes the target's next attack roll is not yet represented as a consumable modifier effect."],
  },
  "dnd.srd521.spell.thunderwave": {
    spellId: "dnd.srd521.spell.thunderwave",
    baseLevel: 1,
    runtimeSupport: "partial",
    castingEconomy: "action",
    targeting: {
      kind: "creature",
      rangeFeet: 15,
      minTargets: 1,
      maxTargets: 64,
      allowedRelations: ["ally", "enemy", "neutral"],
      directTarget: false,
    },
    primary: {
      kind: "save-damage",
      saveAbility: "con",
      damageType: "thunder",
      dice: { count: 2, sides: 8, dicePerSlotAboveBase: 1 },
      successDamage: "half",
    },
    unsupportedInteractions: ["The failed-save 10-foot push needs authoritative forced-movement geometry before this spell can execute completely."],
  },
};

export function spellMechanicById(spellId: string) {
  return SRD_521_SPELL_MECHANICS[spellId];
}
