// Generated by scripts/generate-client-builtin-modules.mjs — do not edit by hand.
// Every SRD 5.2.1 module built from the source (content/modules/srd-5.2.1), in name order.
import m_classes from "../../content/modules/srd-5.2.1/classes.module.json";
import m_core from "../../content/modules/srd-5.2.1/core.module.json";
import m_equipment from "../../content/modules/srd-5.2.1/equipment.module.json";
import m_monsters from "../../content/modules/srd-5.2.1/monsters.module.json";
import m_origins from "../../content/modules/srd-5.2.1/origins.module.json";
import m_rules from "../../content/modules/srd-5.2.1/rules.module.json";
import m_spells from "../../content/modules/srd-5.2.1/spells.module.json";

export const BUILTIN_MODULE_JSON: readonly unknown[] = [
  m_classes,
  m_core,
  m_equipment,
  m_monsters,
  m_origins,
  m_rules,
  m_spells,
];
