// Generated by scripts/generate-client-builtin-modules.mjs — do not edit by hand.
// Every SRD 5.2.1 RuleModule shipped under content/modules, in name order.
import m_dnd_srd_5_2_1_class_feature_common_play from "../../content/modules/dnd-srd-5.2.1.class-feature-common-play/module.json";
import m_dnd_srd_5_2_1_classes from "../../content/modules/dnd-srd-5.2.1.classes/module.json";
import m_dnd_srd_5_2_1_core from "../../content/modules/dnd-srd-5.2.1.core/module.json";
import m_dnd_srd_5_2_1_effect_common_play from "../../content/modules/dnd-srd-5.2.1.effect-common-play/module.json";
import m_dnd_srd_5_2_1_equipment_adventuring_core from "../../content/modules/dnd-srd-5.2.1.equipment-adventuring-core/module.json";
import m_dnd_srd_5_2_1_equipment_armor from "../../content/modules/dnd-srd-5.2.1.equipment-armor/module.json";
import m_dnd_srd_5_2_1_equipment_books from "../../content/modules/dnd-srd-5.2.1.equipment-books/module.json";
import m_dnd_srd_5_2_1_equipment_martial_melee from "../../content/modules/dnd-srd-5.2.1.equipment-martial-melee/module.json";
import m_dnd_srd_5_2_1_equipment_martial_ranged from "../../content/modules/dnd-srd-5.2.1.equipment-martial-ranged/module.json";
import m_dnd_srd_5_2_1_equipment_packs from "../../content/modules/dnd-srd-5.2.1.equipment-packs/module.json";
import m_dnd_srd_5_2_1_equipment_rations from "../../content/modules/dnd-srd-5.2.1.equipment-rations/module.json";
import m_dnd_srd_5_2_1_equipment_simple_melee from "../../content/modules/dnd-srd-5.2.1.equipment-simple-melee/module.json";
import m_dnd_srd_5_2_1_equipment_simple_ranged from "../../content/modules/dnd-srd-5.2.1.equipment-simple-ranged/module.json";
import m_dnd_srd_5_2_1_equipment_starting_utility from "../../content/modules/dnd-srd-5.2.1.equipment-starting-utility/module.json";
import m_dnd_srd_5_2_1_equipment_tools from "../../content/modules/dnd-srd-5.2.1.equipment-tools/module.json";
import m_dnd_srd_5_2_1_feats from "../../content/modules/dnd-srd-5.2.1.feats/module.json";
import m_dnd_srd_5_2_1_origins from "../../content/modules/dnd-srd-5.2.1.origins/module.json";
import m_dnd_srd_5_2_1_spells_a_alarm_alter from "../../content/modules/dnd-srd-5.2.1.spells-a-alarm-alter/module.json";
import m_dnd_srd_5_2_1_spells_a_animal_1 from "../../content/modules/dnd-srd-5.2.1.spells-a-animal-1/module.json";
import m_dnd_srd_5_2_1_spells_a_animal_shapes from "../../content/modules/dnd-srd-5.2.1.spells-a-animal-shapes/module.json";
import m_dnd_srd_5_2_1_spells_a_animate_dead from "../../content/modules/dnd-srd-5.2.1.spells-a-animate-dead/module.json";
import m_dnd_srd_5_2_1_spells_a_animate_objects from "../../content/modules/dnd-srd-5.2.1.spells-a-animate-objects/module.json";
import m_dnd_srd_5_2_1_spells_a_antimagic from "../../content/modules/dnd-srd-5.2.1.spells-a-antimagic/module.json";
import m_dnd_srd_5_2_1_spells_a_antipathy_eye from "../../content/modules/dnd-srd-5.2.1.spells-a-antipathy-eye/module.json";
import m_dnd_srd_5_2_1_spells_a_arcane_hand_lock from "../../content/modules/dnd-srd-5.2.1.spells-a-arcane-hand-lock/module.json";
import m_dnd_srd_5_2_1_spells_a_arcane_sword_aura from "../../content/modules/dnd-srd-5.2.1.spells-a-arcane-sword-aura/module.json";
import m_dnd_srd_5_2_1_spells_a_astral_projection from "../../content/modules/dnd-srd-5.2.1.spells-a-astral-projection/module.json";
import m_dnd_srd_5_2_1_spells_a_aura_of_life from "../../content/modules/dnd-srd-5.2.1.spells-a-aura-of-life/module.json";
import m_dnd_srd_5_2_1_spells_a_awaken from "../../content/modules/dnd-srd-5.2.1.spells-a-awaken/module.json";
import m_dnd_srd_5_2_1_spells_a_core from "../../content/modules/dnd-srd-5.2.1.spells-a-core/module.json";
import m_dnd_srd_5_2_1_starting_loadout_rogue from "../../content/modules/dnd-srd-5.2.1.starting-loadout-rogue/module.json";
import m_dnd_srd_5_2_1_starting_loadout_sorcerer from "../../content/modules/dnd-srd-5.2.1.starting-loadout-sorcerer/module.json";
import m_dnd_srd_5_2_1_starting_loadouts_a from "../../content/modules/dnd-srd-5.2.1.starting-loadouts-a/module.json";
import m_dnd_srd_5_2_1_starting_loadouts_b from "../../content/modules/dnd-srd-5.2.1.starting-loadouts-b/module.json";
import m_dnd_srd_5_2_1_starting_loadouts_backgrounds from "../../content/modules/dnd-srd-5.2.1.starting-loadouts-backgrounds/module.json";
import m_dnd_srd_5_2_1_starting_loadouts_d from "../../content/modules/dnd-srd-5.2.1.starting-loadouts-d/module.json";
import m_dnd_srd_5_2_1_subclasses from "../../content/modules/dnd-srd-5.2.1.subclasses/module.json";

export const BUILTIN_MODULE_JSON: readonly unknown[] = [
  m_dnd_srd_5_2_1_class_feature_common_play,
  m_dnd_srd_5_2_1_classes,
  m_dnd_srd_5_2_1_core,
  m_dnd_srd_5_2_1_effect_common_play,
  m_dnd_srd_5_2_1_equipment_adventuring_core,
  m_dnd_srd_5_2_1_equipment_armor,
  m_dnd_srd_5_2_1_equipment_books,
  m_dnd_srd_5_2_1_equipment_martial_melee,
  m_dnd_srd_5_2_1_equipment_martial_ranged,
  m_dnd_srd_5_2_1_equipment_packs,
  m_dnd_srd_5_2_1_equipment_rations,
  m_dnd_srd_5_2_1_equipment_simple_melee,
  m_dnd_srd_5_2_1_equipment_simple_ranged,
  m_dnd_srd_5_2_1_equipment_starting_utility,
  m_dnd_srd_5_2_1_equipment_tools,
  m_dnd_srd_5_2_1_feats,
  m_dnd_srd_5_2_1_origins,
  m_dnd_srd_5_2_1_spells_a_alarm_alter,
  m_dnd_srd_5_2_1_spells_a_animal_1,
  m_dnd_srd_5_2_1_spells_a_animal_shapes,
  m_dnd_srd_5_2_1_spells_a_animate_dead,
  m_dnd_srd_5_2_1_spells_a_animate_objects,
  m_dnd_srd_5_2_1_spells_a_antimagic,
  m_dnd_srd_5_2_1_spells_a_antipathy_eye,
  m_dnd_srd_5_2_1_spells_a_arcane_hand_lock,
  m_dnd_srd_5_2_1_spells_a_arcane_sword_aura,
  m_dnd_srd_5_2_1_spells_a_astral_projection,
  m_dnd_srd_5_2_1_spells_a_aura_of_life,
  m_dnd_srd_5_2_1_spells_a_awaken,
  m_dnd_srd_5_2_1_spells_a_core,
  m_dnd_srd_5_2_1_starting_loadout_rogue,
  m_dnd_srd_5_2_1_starting_loadout_sorcerer,
  m_dnd_srd_5_2_1_starting_loadouts_a,
  m_dnd_srd_5_2_1_starting_loadouts_b,
  m_dnd_srd_5_2_1_starting_loadouts_backgrounds,
  m_dnd_srd_5_2_1_starting_loadouts_d,
  m_dnd_srd_5_2_1_subclasses,
];
