import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import "../../src/app/connectedActionRoutingAdapter";
import { MockAdapter } from "../../src/app/mockAdapter";
import { applyAdapterRuntimeEffectApplication } from "../../src/app/realRuntimeEffectApplicationService";
import { applyConnectedClientEvents, connectedManifest } from "../../src/app/connectedSessionRuntimeAdapter";
import { connectedStateFor } from "../../src/app/connectedSessionState";
import { ClientSessionReplica, HostSessionLedger, type ConnectedSessionEvent } from "../../src/app/connectedSessionProtocol";
import { tauriSessionTransport } from "../../src/app/tauriSessionTransport";

async function inspiredFighter(identity={sourceId:"feature:bard.bardic-inspiration",effectId:"effect:test-bardic-inspiration",tag:"bardic-inspiration",label:"바드의 영감"}){const adapter=new MockAdapter();await adapter.getSnapshot();await adapter.startInitiative();await adapter.setCurrentActor("char.aelar");await adapter.selectDmActor("char.aelar");const seeded=await applyAdapterRuntimeEffectApplication(adapter,{resolutionId:"seed.inspiration",actorId:"char.aelar",sourceId:identity.sourceId,operations:[{id:"inspiration",kind:"apply-effect",effect:{id:identity.effectId,sourceId:identity.sourceId,sourceActorId:"combatant.bard",targetId:"char.aelar",kind:"marker",tags:[identity.tag],duration:{kind:"hours",amount:1},metadata:{dieSides:8,displayName:identity.label,publicLabel:`${identity.label} · d8`,d20FollowUp:"failed-test-add-die",d20Families:"ability-check,saving-throw,attack-roll",consumeOnUse:true}}}]});assert.equal(seeded.status,"committed");return adapter;}
function attackId(snapshot:Awaited<ReturnType<MockAdapter["getSnapshot"]>>){const action=snapshot.scene.actionsByActor["char.aelar"]?.find((entry)=>entry.runtimeAttack&&entry.resolutionKind==="attack");assert.ok(action);return action.id;}

test("failed attack offers Bardic Inspiration, consumes it, converts the miss, and Undo restores the die",async()=>{const adapter=await inspiredFighter();let snapshot=await adapter.getSnapshot();const actionId=attackId(snapshot);const beforeHp=snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!.hp;await adapter.setQueuedD20(5);await adapter.resolveAction(actionId,["combatant.goblin-a"]);await adapter.advanceResolution();snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.interrupt?.id,"follow-up.effect-d20-bonus");await adapter.setQueuedD20(8);await adapter.respondToInterrupt(true);snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.attackOutcome,"명중");assert.equal(snapshot.resolution?.attackTotal,20);await adapter.advanceResolution();await adapter.advanceResolution();snapshot=await adapter.getSnapshot();assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!.hp<beforeHp);assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="char.aelar")?.status.some((entry)=>entry.includes("바드의 영감")),false);await adapter.undoLastResolution();snapshot=await adapter.getSnapshot();assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!.hp,beforeHp);assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="char.aelar")?.status.some((entry)=>entry.includes("바드의 영감")));});

test("declining Bardic Inspiration preserves the die and the miss",async()=>{const adapter=await inspiredFighter();const actionId=attackId(await adapter.getSnapshot());await adapter.setQueuedD20(5);await adapter.resolveAction(actionId,["combatant.goblin-a"]);await adapter.advanceResolution();await adapter.respondToInterrupt(false);const snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.attackOutcome,"빗나감");assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="char.aelar")?.status.some((entry)=>entry.includes("바드의 영감")));});

test("unknown effect identity uses the same consumable d20 bonus production path",async()=>{const sourceId="external.unknown.effect-source";const adapter=await inspiredFighter({sourceId,effectId:"external.unknown.effect-instance",tag:"external-unknown-tag",label:"외부 보너스"});const actionId=attackId(await adapter.getSnapshot());await adapter.setQueuedD20(5);await adapter.resolveAction(actionId,["combatant.goblin-a"]);await adapter.advanceResolution();assert.equal((await adapter.getSnapshot()).resolution?.interrupt?.source,sourceId);await adapter.setQueuedD20(8);await adapter.respondToInterrupt(true);const snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.attackOutcome,"명중");assert.equal(snapshot.resolution?.attackTotal,20);assert.deepEqual(snapshot.resolution?.rollModifierContributions,[{source:sourceId,value:8}]);});

test("connected Bardic Inspiration follow-up applies the effect removal and attack exactly once",async()=>{const sessionId="session.bardic-follow-up";const host=await inspiredFighter();const actionId=attackId(await host.getSnapshot());const hostState=connectedStateFor(host);hostState.mode="host";hostState.sessionId=sessionId;hostState.ledger=new HostSessionLedger(sessionId,connectedManifest(host));const wires:string[]=[];const send=tauriSessionTransport.send;tauriSessionTransport.send=async(message)=>{wires.push(message);return 1;};try{await host.setQueuedD20(5);await host.resolveAction(actionId,["combatant.goblin-a"]);await host.advanceResolution();await host.setQueuedD20(8);await host.respondToInterrupt(true);await host.advanceResolution();await host.advanceResolution();}finally{tauriSessionTransport.send=send;}const decoded=wires.map((wire)=>JSON.parse(wire));const batch=decoded.find((wire)=>wire.type==="event-batch") as {events:ConnectedSessionEvent[]}|undefined;assert.ok(batch,JSON.stringify(decoded));const client=await inspiredFighter();const before=(await client.getSnapshot()).scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!.hp;const state=connectedStateFor(client);state.mode="client";state.sessionId=sessionId;state.replica=new ClientSessionReplica(sessionId);const applied=await applyConnectedClientEvents(client,batch.events);assert.equal(applied.status,"applied",JSON.stringify(applied));assert.equal((await applyConnectedClientEvents(client,batch.events)).status,"duplicate");const snapshot=await client.getSnapshot();assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!.hp<before);assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="char.aelar")?.status.some((entry)=>entry.includes("바드의 영감")),false);});
