import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import "../../src/app/connectedSessionRuntimeAdapter";
import "../../src/app/connectedActionRoutingAdapter";
import { applyConnectedClientEvents, connectedManifest } from "../../src/app/connectedSessionRuntimeAdapter";
import { connectedStateFor } from "../../src/app/connectedSessionState";
import { ClientSessionReplica, HostSessionLedger, type ConnectedSessionEvent } from "../../src/app/connectedSessionProtocol";
import { catalogQualifiedId } from "../../src/app/contentCatalogIdentity";
import { installedCommonPlayActionId } from "../../src/app/installedCommonPlayActionReference";
import { setInstalledContentStoreForTests } from "../../src/app/installedContentRuntimeAdapter";
import { MemoryInstalledContentStore } from "../../src/app/memoryInstalledContentStore";
import { MockAdapter } from "../../src/app/mockAdapter";
import { tauriSessionTransport } from "../../src/app/tauriSessionTransport";
import { snapshotAdapterTurnRuntimeState } from "../../src/app/turnRuntimeSessionRegistry";
import { commonPlayVehicleSpeed } from "../../src/domain/commonPlayMountRuntime";

function payload(prefix:string){
  const moduleId=`${prefix}.module`,actionContent=`${prefix}.mount-action-content`,actionMechanic=`${prefix}.mount-actions`;
  const mountActionId=installedCommonPlayActionId({catalogId:catalogQualifiedId(actionContent,moduleId,"1"),mechanicId:actionMechanic,entryPointId:"kick"});
  const topologyContent=`${prefix}.topology-content`,topologyMechanic=`${prefix}.topology`;
  const action=(entryPointId:string)=>installedCommonPlayActionId({catalogId:catalogQualifiedId(topologyContent,moduleId,"1"),mechanicId:topologyMechanic,entryPointId});
  return {mountId:`${prefix}.mount`,createActionId:action("create"),dismountActionId:action("dismount"),fallActionId:action("fall-off"),independentActionId:action("independent"),json:JSON.stringify({schemaVersion:"0.1-draft",moduleId,moduleVersion:"1",rulesProfile:{id:"dnd.srd-5.2.1",version:"0.1-draft"},defaultLocale:"en",source:{document:"Family AD",version:"1",license:"CC0",srdDerived:false},dependencies:[],conflicts:[],capabilities:[],content:[
    {id:topologyContent,category:"option",presentation:{defaultLocale:"en",locales:{en:{name:"Unknown mount topology"}}},mechanics:[{kind:"common-play",config:{schemaVersion:"0.2-draft",id:topologyMechanic,entryPoints:[
      {id:"create",invocation:"manual",operations:[{kind:"movement.spend",target:"self",amount:{value:15},activity:"mount"},{kind:"artifact.spawn",template:"mount"},{kind:"artifact.spawn",template:"vehicle"},{kind:"artifact.spawn",template:"riding"},{kind:"artifact.spawn",template:"drawn"}]},
      {id:"dismount",invocation:"manual",operations:[{kind:"movement.spend",target:"self",amount:{value:15},activity:"dismount"},{kind:"artifact.remove",artifact:"riding"}]},
      {id:"fall-off",invocation:"manual",test:{kind:"saving-throw",roller:"actor",property:"save.dex.modifier",dc:{value:100}},operations:[{kind:"condition.apply",condition:"prone",target:"self",when:{op:"eq",left:{ref:"test.outcome"},right:{value:"failure"}}},{kind:"artifact.remove",artifact:"riding"}]},
      {id:"independent",invocation:"manual",operations:[{kind:"movement.spend",target:"self",amount:{value:15},activity:"mount"},{kind:"artifact.spawn",template:"independent-mount"},{kind:"artifact.spawn",template:"independent-riding"}]},
    ],artifactTemplates:[
      {id:"mount",artifactKind:"actor",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{combatantId:`${prefix}.mount`,statDefinitionId:`${prefix}.mount-stat`,ownerId:"actor",controllerId:"actor",side:"ally",initiative:"shared",properties:{"presentation.name":"Unknown Mount","defense.ac":12,"hp.maximum":20,"movement.walk":60},actionDefinitionIds:[mountActionId],resources:[]}},
      {id:"vehicle",artifactKind:"object",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{size:"large",armorClass:15,hp:{current:30,maximum:30},damageThreshold:5,repairable:true}},
      {id:"riding",artifactKind:"link",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{endpointIds:["actor","artifact:mount"],relation:"mount",mount:{controllerId:"actor",mode:"controlled",riderSize:"medium",mountSize:"large",movementCostFeet:15,controlledActionIds:[mountActionId]}}},
      {id:"drawn",artifactKind:"link",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{endpointIds:["artifact:mount","artifact:vehicle"],relation:"drawn-vehicle",vehicle:{capacityPounds:1000,minimumCrew:1,crewIds:["actor"],speedFeet:40}}},
      {id:"independent-mount",artifactKind:"actor",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{combatantId:`${prefix}.independent-mount`,statDefinitionId:`${prefix}.independent-stat`,ownerId:"actor",controllerId:"actor",side:"ally",initiative:"independent",properties:{"presentation.name":"Independent Mount","defense.ac":12,"hp.maximum":20,"movement.walk":60,"initiative":12},actionDefinitionIds:[mountActionId],resources:[]}},
      {id:"independent-riding",artifactKind:"link",duration:{kind:"durable"},lifetime:{kind:"durable"},initialState:{endpointIds:["actor","artifact:independent-mount"],relation:"mount",mount:{controllerId:"actor",mode:"independent",riderSize:"medium",mountSize:"large",movementCostFeet:15,controlledActionIds:[mountActionId]}}},
    ]}}]},
    {id:actionContent,category:"option",presentation:{defaultLocale:"en",locales:{en:{name:"Unknown Mount Kick"}}},mechanics:[{kind:"common-play",config:{schemaVersion:"0.2-draft",id:actionMechanic,entryPoints:[{id:"kick",invocation:"manual",operations:[{kind:"healing.apply",amount:{value:1},target:"self"}]}]}}]},
  ]})};
}

async function setup(prefix:string){const adapter=new MockAdapter(),pack=payload(prefix);setInstalledContentStoreForTests(adapter,new MemoryInstalledContentStore());const preview=await adapter.previewContentImport(pack.json);assert.ok(!preview.contentImport?.validation.some((entry)=>entry.severity==="blocking"),JSON.stringify(preview.contentImport?.validation));await adapter.activateContentImport();await adapter.startInitiative();await adapter.setCurrentActor("char.aelar");return {adapter,pack};}
async function capture(adapter:MockAdapter,op:()=>Promise<unknown>){const state=connectedStateFor(adapter);assert.ok(state.ledger);const cursor=state.ledger.cursor,send=tauriSessionTransport.send;tauriSessionTransport.send=async()=>1;try{await op();}finally{tauriSessionTransport.send=send;}const events=state.ledger.eventsAfter(cursor);assert.ok(events.length);return events as ConnectedSessionEvent[];}
function topology(adapter:MockAdapter,snapshot:Awaited<ReturnType<MockAdapter["getSnapshot"]>>,prefix:string){const state=snapshotAdapterTurnRuntimeState(adapter,snapshot.scene);const riding=state?.artifacts?.find((artifact)=>artifact.link?.relation==="mount")?.link,drawn=state?.artifacts?.find((artifact)=>artifact.link?.relation==="drawn-vehicle")?.link;return {rider:riding?.endpointIds[0],controller:riding?.mount?.controllerId,mode:riding?.mount?.mode,cost:riding?.mount?.movementCostFeet,mountActions:snapshot.scene.actionsByActor[`${prefix}.mount`]?.length??0,vehicleSpeed:drawn?.vehicle?commonPlayVehicleSpeed({draftActorId:drawn.endpointIds[0],vehicleId:drawn.endpointIds[1],...drawn.vehicle}):undefined,capacity:drawn?.vehicle?.capacityPounds};}

async function run(prefix:string){const {adapter,pack}=await setup(prefix);await adapter.resolveAction(pack.createActionId,["char.aelar"]);const mounted=snapshotAdapterTurnRuntimeState(adapter,(await adapter.getSnapshot()).scene);assert.equal(mounted?.combatants["char.aelar"].economy.movement,15);const result=topology(adapter,await adapter.getSnapshot(),prefix);await adapter.resolveAction(pack.dismountActionId,["char.aelar"]);const dismounted=snapshotAdapterTurnRuntimeState(adapter,(await adapter.getSnapshot()).scene);assert.equal(dismounted?.combatants["char.aelar"].economy.movement,0);assert.equal(dismounted?.artifacts?.some((artifact)=>artifact.link?.relation==="mount"),false);await adapter.undoLastResolution();assert.equal(snapshotAdapterTurnRuntimeState(adapter,(await adapter.getSnapshot()).scene)?.artifacts?.some((artifact)=>artifact.link?.relation==="mount"),true);await adapter.resolveAction(pack.fallActionId,["char.aelar"]);const fallen=snapshotAdapterTurnRuntimeState(adapter,(await adapter.getSnapshot()).scene);assert.equal(fallen?.artifacts?.some((artifact)=>artifact.link?.relation==="mount"),false);assert.ok(fallen?.effects.some((effect)=>effect.targetId==="char.aelar"&&effect.conditionId==="prone"));await adapter.undoLastResolution();const restored=snapshotAdapterTurnRuntimeState(adapter,(await adapter.getSnapshot()).scene);assert.equal(restored?.artifacts?.some((artifact)=>artifact.link?.relation==="mount"),true);assert.equal(restored?.effects.some((effect)=>effect.targetId==="char.aelar"&&effect.conditionId==="prone"),false);return result;}

test("portable mount and drawn vehicle topology composes existing actor/object/link authorities independent of identity",async()=>{const expected={rider:"char.aelar",controller:"char.aelar",mode:"controlled",cost:15,mountActions:1,vehicleSpeed:40,capacity:1000};assert.deepEqual(await run("external.mount"),expected);assert.deepEqual(await run("renamed.transport"),expected);});

test("independent mount retains its own initiative and action owner without identity dispatch",async()=>{for(const prefix of ["external.independent","renamed.independent"]){const {adapter,pack}=await setup(prefix);await adapter.resolveAction(pack.independentActionId,["char.aelar"]);const snapshot=await adapter.getSnapshot(),state=snapshotAdapterTurnRuntimeState(adapter,snapshot.scene),artifact=state?.artifacts?.find((candidate)=>candidate.actor?.combatantId===`${prefix}.independent-mount`),link=state?.artifacts?.find((candidate)=>candidate.link?.mount?.mode==="independent");assert.equal(artifact?.actor?.initiative,"independent");assert.equal(state?.combatants[`${prefix}.independent-mount`].baseProperties?.initiative,12);assert.equal(link?.link?.mount?.controllerId,"char.aelar");assert.equal(snapshot.scene.actionsByActor[`${prefix}.independent-mount`]?.length,1);}});

test("mount and vehicle topology survives connected replay, reconnect, duplicate delivery, and Undo",async()=>{const prefix="external.connected-mount",sessionId="session.family-ad",{adapter:host,pack}=await setup(prefix),hostState=connectedStateFor(host);hostState.mode="host";hostState.sessionId=sessionId;hostState.ledger=new HostSessionLedger(sessionId,connectedManifest(host));const batch=await capture(host,()=>host.resolveAction(pack.createActionId,["char.aelar"]));const {adapter:client}=await setup(prefix),clientState=connectedStateFor(client);clientState.mode="client";clientState.sessionId=sessionId;clientState.replica=new ClientSessionReplica(sessionId);assert.equal((await applyConnectedClientEvents(client,batch)).status,"applied");assert.deepEqual(topology(client,await client.getSnapshot(),prefix),topology(host,await host.getSnapshot(),prefix));assert.equal((await applyConnectedClientEvents(client,batch)).status,"duplicate");const {adapter:reconnect}=await setup(prefix),reconnectState=connectedStateFor(reconnect);reconnectState.mode="client";reconnectState.sessionId=sessionId;reconnectState.replica=new ClientSessionReplica(sessionId);assert.equal((await applyConnectedClientEvents(reconnect,hostState.ledger.eventsAfter(0))).status,"applied");assert.deepEqual(topology(reconnect,await reconnect.getSnapshot(),prefix),topology(host,await host.getSnapshot(),prefix));const undone=await capture(host,()=>host.undoLastResolution());assert.equal((await applyConnectedClientEvents(client,undone)).status,"applied");assert.equal(snapshotAdapterTurnRuntimeState(client,(await client.getSnapshot()).scene)?.artifacts?.some((artifact)=>artifact.link?.relation==="mount"),false);});
