import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import { catalogQualifiedId } from "../../src/app/contentCatalogIdentity";
import { installedCommonPlayActionId } from "../../src/app/installedCommonPlayActionReference";
import { setInstalledContentStoreForTests } from "../../src/app/installedContentRuntimeAdapter";
import { MemoryInstalledContentStore } from "../../src/app/memoryInstalledContentStore";
import { MockAdapter } from "../../src/app/mockAdapter";
import { runtimeResolutionEventHistory } from "../../src/app/runtimeResolutionEventHistory";
import { snapshotAdapterTurnRuntimeState } from "../../src/app/turnRuntimeSessionRegistry";
const TARGET_ID="combatant.goblin-a";
function payload(prefix:string){const moduleId=`${prefix}.module`,contentId=`${prefix}.mastery-probe`,mechanicId=`${prefix}.mechanic`;return{moduleId,contentId,mechanicId,json:JSON.stringify({schemaVersion:"0.1-draft",moduleId,moduleVersion:"1",rulesProfile:{id:"dnd.srd-5.2.1",version:"0.1-draft"},defaultLocale:"en",source:{document:"Family K outcome-conditioned damage probe",version:"1",license:"CC0",srdDerived:false},dependencies:[],conflicts:[],capabilities:[],content:[{id:contentId,category:"option",presentation:{defaultLocale:"en",originalName:"Portable Mastery Probe",locales:{en:{name:"Portable Mastery Probe"}}},mechanics:[{kind:"common-play",config:{schemaVersion:"0.2-draft",id:mechanicId,entryPoints:[{id:"graze-like-miss-rider",invocation:"manual",targeting:{from:"targets",min:1,max:1},test:{kind:"attack-roll",roller:"actor",dc:{value:10}},operations:[{kind:"damage.apply",amount:{value:3},damageType:"force",target:"target",when:{op:"eq",left:{ref:"test.outcome"},right:{value:"failure"}}}]}]}}]}]})};}
async function prepare(prefix:string){const adapter=new MockAdapter(),pack=payload(prefix);setInstalledContentStoreForTests(adapter,new MemoryInstalledContentStore());const preview=await adapter.previewContentImport(pack.json);assert.ok(!preview.contentImport?.validation.some((e)=>e.severity==="blocking"),JSON.stringify(preview.contentImport?.validation));await adapter.activateContentImport();await adapter.startInitiative();await adapter.setCurrentActor("char.aelar");return{adapter,actionId:installedCommonPlayActionId({catalogId:catalogQualifiedId(pack.contentId,pack.moduleId,"1"),mechanicId:pack.mechanicId,entryPointId:"graze-like-miss-rider"})};}
function hp(adapter:MockAdapter,snapshot:Awaited<ReturnType<MockAdapter["getSnapshot"]>>){const target=snapshotAdapterTurnRuntimeState(adapter,snapshot.scene)?.combatants[TARGET_ID];assert.ok(target);return target.life.hp.current;}
async function exercise(prefix:string,face:number){const{adapter,actionId}=await prepare(prefix);let snapshot=await adapter.getSnapshot();const before=hp(adapter,snapshot);await adapter.setQueuedD20(face);snapshot=await adapter.resolveAction(actionId,[TARGET_ID]);assert.equal(snapshot.resolution?.stage,"complete",JSON.stringify(snapshot.resolution));const after=hp(adapter,snapshot);const changes=runtimeResolutionEventHistory(adapter)?.events.filter((e)=>e.stateChanges.some((c)=>c.kind==="hp"&&c.field==="current"&&c.targetId===TARGET_ID))??[];return{adapter,before,after,changes};}
test("unknown installed Common Play applies Graze-like damage only on attack failure",async()=>{const miss=await exercise("unknown-family-k-graze",1);assert.equal(miss.after,miss.before-3);assert.equal(miss.changes.length,1);await miss.adapter.undoLastResolution();assert.equal(hp(miss.adapter,await miss.adapter.getSnapshot()),miss.before);const hit=await exercise("unknown-family-k-hit",15);assert.equal(hit.after,hit.before);assert.equal(hit.changes.length,0);});
test("outcome-conditioned damage is invariant to external identity",async()=>{const a=await exercise("unknown-family-k-identity-a",1),b=await exercise("renamed-family-k-identity-b",1);assert.equal(a.before-a.after,3);assert.equal(b.before-b.after,3);});
