import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import "../../src/app/connectedSessionRuntimeAdapter";
import "../../src/app/connectedActionRoutingAdapter";
import { catalogQualifiedId } from "../../src/app/contentCatalogIdentity";
import { connectedManifest } from "../../src/app/connectedSessionRuntimeAdapter";
import { connectedStateFor } from "../../src/app/connectedSessionState";
import { installedCommonPlayActionId } from "../../src/app/installedCommonPlayActionReference";
import { setInstalledContentStoreForTests } from "../../src/app/installedContentRuntimeAdapter";
import { MemoryInstalledContentStore } from "../../src/app/memoryInstalledContentStore";
import { MockAdapter } from "../../src/app/mockAdapter";
import { HostSessionLedger } from "../../src/app/connectedSessionProtocol";
import { tauriSessionTransport } from "../../src/app/tauriSessionTransport";
import { routeConnectedInterruptResponse } from "../../src/app/connectedInterruptResponsePort";

type AuthorityResponder="dm"|"host";
const MODULE_ID="homebrew.authority-responder",CONTENT_ID="option.authority-responder",MECHANIC_ID="external.unknown.authority-responder",ENTRY_POINT_ID="ask-authority";
function payload(responder:AuthorityResponder){return JSON.stringify({schemaVersion:"0.1-draft",moduleId:`${MODULE_ID}.${responder}`,moduleVersion:"1",rulesProfile:{id:"dnd.srd-5.2.1",version:"0.1-draft"},defaultLocale:"en",source:{document:"Authority Responder Probe",version:"1",license:"CC0",srdDerived:false},dependencies:[],conflicts:[],capabilities:[],content:[{id:`${CONTENT_ID}.${responder}`,category:"option",presentation:{defaultLocale:"en",originalName:`${responder} Authority Consent`,locales:{en:{name:`${responder} Authority Consent`,description:"Portable local authority consent probe"}}},mechanics:[{kind:"common-play",config:{schemaVersion:"0.2-draft",id:`${MECHANIC_ID}.${responder}`,payments:[{kind:"economy",bucket:"reaction",amount:{value:1},consumeAt:"commit",refundOnCancel:true}],entryPoints:[{id:ENTRY_POINT_ID,invocation:"manual",interaction:{id:`authority-consent.${responder}`,kind:"consent",responder,mode:"blocking",input:{type:"boolean"},revalidate:"if-revision-changed",stalePolicy:"reject"},operations:[{kind:"damage.apply",amount:{value:1},damageType:"force",target:"actor"}]}]}}]}]});}
async function install(adapter:MockAdapter,responder:AuthorityResponder){setInstalledContentStoreForTests(adapter,new MemoryInstalledContentStore());const preview=await adapter.previewContentImport(payload(responder));assert.ok(!preview.contentImport?.validation.some((entry)=>entry.severity==="blocking"),JSON.stringify(preview.contentImport?.validation));await adapter.activateContentImport();return installedCommonPlayActionId({catalogId:catalogQualifiedId(`${CONTENT_ID}.${responder}`,`${MODULE_ID}.${responder}`,"1"),mechanicId:`${MECHANIC_ID}.${responder}`,entryPointId:ENTRY_POINT_ID});}
async function setup(responder:AuthorityResponder){const adapter=new MockAdapter();await adapter.startProductionLocalPlay("dm");const actionId=await install(adapter,responder);const internal=adapter as unknown as {activeCharacter:{id:string};role:"player"|"dm"};const actorId=internal.activeCharacter.id;await adapter.startInitiative();await adapter.setCurrentActor(actorId);const sessionId=`session.authority.${responder}`;const state=connectedStateFor(adapter);state.mode="host";state.sessionId=sessionId;state.ledger=new HostSessionLedger(sessionId,connectedManifest(adapter));state.peerManifests.set("peer.actor",structuredClone(connectedManifest(adapter)));return {adapter,actionId,internal,actorId,sessionId,state};}
async function withTransport<T>(fn:(direct:Array<{peer:string;message:string}>,broadcasts:string[])=>Promise<T>){const direct:Array<{peer:string;message:string}>=[],broadcasts:string[]=[];const oldSend=tauriSessionTransport.send,oldSendTo=tauriSessionTransport.sendTo;tauriSessionTransport.send=async(message)=>{broadcasts.push(message);return 1;};tauriSessionTransport.sendTo=async(peer,message)=>{direct.push({peer,message});return 1;};try{return await fn(direct,broadcasts);}finally{tauriSessionTransport.send=oldSend;tauriSessionTransport.sendTo=oldSendTo;}}

for(const responder of ["dm","host"] as const) test(`${responder} responder remains local authority and remote Character peers cannot approve it`,async()=>withTransport(async(direct,broadcasts)=>{const {adapter,actionId,actorId,sessionId}=await setup(responder);const before=await adapter.getSnapshot(),tempHpBefore=before.activeCharacter.tempHp;assert.equal(before.scene.economyByActor[actorId]?.reaction,true);let snapshot=await adapter.resolveAction(actionId,[actorId]);assert.equal(snapshot.resolution?.stage,"interrupt",JSON.stringify(snapshot.resolution));assert.equal(snapshot.resolution?.interrupt?.responderId,`authority:${responder}`);assert.ok(!direct.map((entry)=>JSON.parse(entry.message)).some((wire)=>wire.type==="resolution-interrupt-prompt"),JSON.stringify(direct));const resolutionId=snapshot.resolution!.id,promptId=snapshot.resolution!.interrupt!.id,directBefore=direct.length;assert.equal(await routeConnectedInterruptResponse(adapter,{peer:"peer.actor",message:""},{sessionId,resolutionId,promptId,accept:true}),true);const errors=direct.slice(directBefore).map((entry)=>JSON.parse(entry.message)).filter((wire)=>wire.type==="error");assert.equal(errors.at(-1)?.code,"interrupt-not-authorized",JSON.stringify(errors));snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.stage,"interrupt");assert.equal(snapshot.activeCharacter.tempHp,tempHpBefore);snapshot=await adapter.respondToInterrupt(true);assert.equal(snapshot.resolution?.stage,"complete",JSON.stringify(snapshot.resolution));assert.equal(snapshot.activeCharacter.tempHp,tempHpBefore-1);assert.equal(snapshot.scene.economyByActor[actorId]?.reaction,false);assert.ok(broadcasts.map((wire)=>JSON.parse(wire)).some((wire)=>wire.type==="event-batch"),JSON.stringify(broadcasts));}));
for(const responder of ["dm","host"] as const) test(`${responder} approval revalidates local authority before commit`,async()=>withTransport(async()=>{const {adapter,actionId,internal,actorId,state}=await setup(responder);let snapshot=await adapter.resolveAction(actionId,[actorId]);assert.equal(snapshot.resolution?.stage,"interrupt",JSON.stringify(snapshot.resolution));const tempHpBefore=snapshot.activeCharacter.tempHp;if(responder==="dm")internal.role="player";else state.mode=null;snapshot=await adapter.respondToInterrupt(true);assert.equal(snapshot.resolution?.stage,"complete",JSON.stringify(snapshot.resolution));assert.match(snapshot.resolution?.finalOutcome??"",/권한 재검증 실패/);assert.equal(snapshot.activeCharacter.tempHp,tempHpBefore);assert.equal(snapshot.scene.economyByActor[actorId]?.reaction,true);}));
