import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import "../../src/app/connectedActionRoutingAdapter";
import { MockAdapter } from "../../src/app/mockAdapter";
import { applyConnectedClientEvents, connectedManifest } from "../../src/app/connectedSessionRuntimeAdapter";
import { connectedStateFor } from "../../src/app/connectedSessionState";
import { ClientSessionReplica, HostSessionLedger, type ConnectedSessionEvent } from "../../src/app/connectedSessionProtocol";
import { tauriSessionTransport } from "../../src/app/tauriSessionTransport";
import { commitAdapterTurnRuntimeState, snapshotAdapterTurnRuntimeState } from "../../src/app/turnRuntimeSessionRegistry";
import { FIGHTER_SECOND_WIND_RESOURCE_ID } from "../../src/domain/coreClassResources";
import type { SceneVm } from "../../src/app/contracts";

function knockOut(adapter:MockAdapter){const scene=(adapter as unknown as {scene:SceneVm}).scene;const target=scene.entities.find((entry)=>entry.id==="combatant.goblin-a")!;target.hp=0;target.runtimeLife={deathSaves:{successes:1,failures:1},stable:false,unconscious:true,dead:false};}
async function preparedFighter(){const adapter=new MockAdapter();knockOut(adapter);await adapter.startInitiative();await adapter.setCurrentActor("char.aelar");await adapter.selectDmActor("char.aelar");const snapshot=await adapter.getSnapshot();const resource=snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID);assert.ok(resource);const internal=adapter as unknown as {scene:SceneVm};const state=snapshotAdapterTurnRuntimeState(adapter,internal.scene)!;const combatant=state.combatants["char.aelar"];if(!combatant.resources.some((entry)=>entry.id===resource.id)){combatant.resources.push({id:resource.id,label:resource.label,current:resource.current,maximum:resource.max,recovery:resource.recovery});const expected=state.revision;state.revision+=1;assert.equal(commitAdapterTurnRuntimeState(adapter,internal.scene,expected,state),true);}return adapter;}

test("failed Stabilize offers Tactical Mind, succeeds, spends Second Wind, and Undo restores all",async()=>{const adapter=await preparedFighter();let snapshot=await adapter.getSnapshot();const beforeUses=snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)!.current;await adapter.setQueuedD20(1);await adapter.resolveAction("action.standard.stabilize",["combatant.goblin-a"]);snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.interrupt?.id,"follow-up.fighter.tactical-mind");await adapter.setQueuedD20(8);await adapter.respondToInterrupt(true);snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.finalOutcome,"안정화 성공");assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.runtimeLife?.stable,true);assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)?.current,beforeUses-1);await adapter.undoLastResolution();snapshot=await adapter.getSnapshot();assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.runtimeLife?.stable,false);assert.equal(snapshot.scene.economyByActor["char.aelar"]?.action,true);assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)?.current,beforeUses);});

test("Tactical Mind preserves Second Wind when the d10 still fails",async()=>{const adapter=await preparedFighter();const before=(await adapter.getSnapshot()).activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)!.current;await adapter.setQueuedD20(1);await adapter.resolveAction("action.standard.stabilize",["combatant.goblin-a"]);await adapter.setQueuedD20(1);await adapter.respondToInterrupt(true);const snapshot=await adapter.getSnapshot();assert.equal(snapshot.resolution?.finalOutcome,"안정화 실패");assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)?.current,before);});

test("declined Tactical Mind is not offered twice for the same failed check",async()=>{const adapter=await preparedFighter();await adapter.setQueuedD20(1);await adapter.resolveAction("action.standard.stabilize",["combatant.goblin-a"]);await adapter.respondToInterrupt(false);await adapter.resolveAction("action.missing",[]);assert.equal((await adapter.getSnapshot()).resolution?.interrupt,undefined);});

test("connected Tactical Mind applies Stabilize and Second Wind exactly once",async()=>{const sessionId="session.tactical-mind";const host=await preparedFighter();const hostState=connectedStateFor(host);hostState.mode="host";hostState.sessionId=sessionId;hostState.ledger=new HostSessionLedger(sessionId,connectedManifest(host));const wires:string[]=[];const send=tauriSessionTransport.send;tauriSessionTransport.send=async(message)=>{wires.push(message);return 1;};try{await host.setQueuedD20(1);await host.resolveAction("action.standard.stabilize",["combatant.goblin-a"]);await host.setQueuedD20(8);await host.respondToInterrupt(true);}finally{tauriSessionTransport.send=send;}const decoded=wires.map((wire)=>JSON.parse(wire));const batch=decoded.find((wire)=>wire.type==="event-batch") as {events:ConnectedSessionEvent[]}|undefined;assert.ok(batch,JSON.stringify(decoded));const client=await preparedFighter();const before=(await client.getSnapshot()).activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)!.current;const state=connectedStateFor(client);state.mode="client";state.sessionId=sessionId;state.replica=new ClientSessionReplica(sessionId);const applied=await applyConnectedClientEvents(client,batch.events);assert.equal(applied.status,"applied",JSON.stringify(applied));assert.equal((await applyConnectedClientEvents(client,batch.events)).status,"duplicate");const snapshot=await client.getSnapshot();assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.runtimeLife?.stable,true);assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===FIGHTER_SECOND_WIND_RESOURCE_ID)?.current,before-1);});
