import assert from "node:assert/strict";
import test from "node:test";
import "../../src/app/offlineRuntimeAdapters";
import "../../src/app/connectedActionRoutingAdapter";
import { MockAdapter } from "../../src/app/mockAdapter";
import type { CharacterSheet, SceneVm } from "../../src/app/contracts";
import { PALADIN_CHANNEL_DIVINITY_RESOURCE_ID, PALADIN_ID } from "../../src/domain/coreClassResources";
import { applyConnectedClientEvents, connectedManifest } from "../../src/app/connectedSessionRuntimeAdapter";
import { connectedStateFor } from "../../src/app/connectedSessionState";
import { ClientSessionReplica, HostSessionLedger, type ConnectedSessionEvent } from "../../src/app/connectedSessionProtocol";
import { tauriSessionTransport } from "../../src/app/tauriSessionTransport";

async function paladin(){const adapter=new MockAdapter();const internal=adapter as unknown as {activeCharacter:CharacterSheet;scene:SceneVm};internal.activeCharacter={...internal.activeCharacter,className:"팔라딘",level:9,classLevels:[{classId:PALADIN_ID,className:"팔라딘",level:9}],abilities:{...internal.activeCharacter.abilities,cha:18},resources:[]};await adapter.getSnapshot();await adapter.startInitiative();await adapter.setCurrentActor(internal.activeCharacter.id);await adapter.selectDmActor(internal.activeCharacter.id);return adapter;}

test("Abjure Foes applies public Frightened, spends Action and Channel Divinity, and Undo restores",async()=>{const adapter=await paladin();let snapshot=await adapter.getSnapshot();const action=snapshot.scene.actionsByActor[snapshot.activeCharacter.id]?.find((entry)=>entry.id==="action.paladin.abjure-foes");assert.equal(action?.maxTargets,4);await adapter.setQueuedD20(1);await adapter.resolveAction("action.paladin.abjure-foes",["combatant.goblin-a"]);snapshot=await adapter.getSnapshot();assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.status.some((entry)=>entry.includes("공포 · 적 질책")));assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===PALADIN_CHANNEL_DIVINITY_RESOURCE_ID)?.current,1);assert.equal(snapshot.scene.economyByActor[snapshot.activeCharacter.id]?.action,false);await adapter.undoLastResolution();snapshot=await adapter.getSnapshot();assert.equal(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.status.some((entry)=>entry.includes("적 질책")),false);assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===PALADIN_CHANNEL_DIVINITY_RESOURCE_ID)?.current,2);assert.equal(snapshot.scene.economyByActor[snapshot.activeCharacter.id]?.action,true);});

test("freeform Abjure Foes does not strand Action",async()=>{const adapter=await paladin();await adapter.setSessionMode("freeform");await adapter.setQueuedD20(1);await adapter.resolveAction("action.paladin.abjure-foes",["combatant.goblin-a"]);const snapshot=await adapter.getSnapshot();assert.equal(snapshot.scene.economyByActor[snapshot.activeCharacter.id]?.action,true);});

test("connected Abjure Foes converges public condition and resource exactly once",async()=>{const sessionId="session.abjure-foes";const host=await paladin();const hostState=connectedStateFor(host);hostState.mode="host";hostState.sessionId=sessionId;hostState.ledger=new HostSessionLedger(sessionId,connectedManifest(host));const wires:string[]=[];const send=tauriSessionTransport.send;tauriSessionTransport.send=async(message)=>{wires.push(message);return 1;};try{await host.setQueuedD20(1);await host.resolveAction("action.paladin.abjure-foes",["combatant.goblin-a"]);}finally{tauriSessionTransport.send=send;}const batch=wires.map((wire)=>JSON.parse(wire)).find((wire)=>wire.type==="event-batch") as {events:ConnectedSessionEvent[]}|undefined;assert.ok(batch);const client=await paladin();const state=connectedStateFor(client);state.mode="client";state.sessionId=sessionId;state.replica=new ClientSessionReplica(sessionId);assert.equal((await applyConnectedClientEvents(client,batch.events)).status,"applied");assert.equal((await applyConnectedClientEvents(client,batch.events)).status,"duplicate");const snapshot=await client.getSnapshot();assert.ok(snapshot.scene.entities.find((entry)=>entry.id==="combatant.goblin-a")?.status.some((entry)=>entry.includes("공포 · 적 질책")));assert.equal(snapshot.activeCharacter.resources.find((entry)=>entry.id===PALADIN_CHANNEL_DIVINITY_RESOURCE_ID)?.current,1);});
