import type { AbilityKey, CharacterCreateDraft, CharacterCreationOptionVm, CharacterCreationPlan, CharacterCreationSection, ValidationMessage } from "./contracts";
import { BACKGROUNDS, CLASSES, FIGHTER, SPECIES, SPELLS, opt, type Option } from "./characterCreationV09Catalog";
import { META, classId, meta } from "./characterCreationV09Meta";
export { FIGHTER, META, classId, meta };
const choose=(xs:Option[],value:string|string[]|undefined)=>{const values=Array.isArray(value)?value:[value];return xs.map((x)=>({...x,selected:values.includes(x.id)||values.includes(x.name)}));};
export function validate(d:CharacterCreateDraft):ValidationMessage[]{const out=d.validation.filter((x)=>!/종족을 선택|배경을 선택|클래스를 선택|전투 방식 Choice|주문 선택은|후보에 없는 기술/.test(x.message)),id=classId(d),m=meta(d);if(!d.species)out.push({severity:"blocking",message:"종족을 선택해야 합니다."});if(!d.background)out.push({severity:"blocking",message:"배경을 선택해야 합니다."});if(!d.className)out.push({severity:"blocking",message:"클래스를 선택해야 합니다."});if(id==="class.fighter"&&(d.selectedClassChoices?.length??0)!==1)out.push({severity:"blocking",message:"현재 레벨의 전투 방식 Choice를 1개 선택해야 합니다."});if((SPELLS[id]?.length??0)>0&&d.selectedSpells.length!==2)out.push({severity:"blocking",message:`현재 레벨 주문 선택은 2개가 필요합니다. 현재 ${d.selectedSpells.length}/2`});const bad=d.selectedSkills.filter((x)=>!m.skills.includes(x));if(bad.length)out.push({severity:"warning",message:`현재 클래스 후보에 없는 기술 숙련: ${bad.join(", ")}`});return out;}
export function normalize(d:CharacterCreateDraft){d.activeSectionId||="identity";d.selectedClassChoices||=[];if(d.level<=1&&!d.editingCharacterId)d.subclassName="";const m=meta(d),dex=Math.floor((d.abilities.dex-10)/2),con=Math.floor((d.abilities.con-10)/2);let ac=10+dex;if(d.equipmentPreset==="chain-shield")ac=18;else if(d.equipmentPreset==="scale-shield")ac=16;else if(["leather-kit","bard-pack"].includes(d.equipmentPreset))ac=11+dex;d.derived={proficiencyBonus:d.level>=5?3:2,hp:d.overrides.hp??Math.max(1,m.hit+con),ac:d.overrides.ac??ac,speed:d.overrides.speed??30};d.validation=validate(d);return d;}
const st=(req:boolean,blocked:boolean,done:boolean,warn=false):CharacterCreationSection["status"]=>blocked?"blocked":warn?"warning":!req?"not-applicable":done?"complete":"incomplete";
export function buildPlan(d:CharacterCreateDraft):CharacterCreationPlan{
 const id=classId(d),m=meta(d),fighter=id==="class.fighter"?FIGHTER:[],spells=SPELLS[id]??[],v=validate(d);
 const mk=(id:string,kind:CharacterCreationSection["kind"],label:string,description:string,status:CharacterCreationSection["status"],required:boolean,dependsOn:string[],options:CharacterCreationOptionVm[]=[],automaticGrants:string[]=[],filter?:RegExp):CharacterCreationSection=>({id,kind,label,description,status,required,dependsOn,options,automaticGrants,validation:filter?v.filter((x)=>filter.test(x.message)):[]});
 const abilityBlock=d.validation.some((x)=>x.severity==="blocking"&&/배열|Roll Slot|포인트 구매/.test(x.message));
 const sections=[
  mk("rules","rules-profile","규칙","규칙 의미와 호환 콘텐츠 범위를 결정합니다.","complete",true,[],[{...opt(d.rulesProfileId,"D&D SRD 5.2.1","D&D SRD 5.2.1","초기 RulesProfile",["ko-KR 기본 표시"]),selected:true}],["RulesProfile identity/version 저장"]),
  mk("identity","identity","정체성","이름과 서술 정보는 규칙 선택과 분리합니다.",st(true,false,!!d.name.trim()),true,[]),
  mk("species","species","종족","종족을 독립적으로 선택합니다.",st(true,false,!!d.species),true,["rules"],choose(SPECIES,d.species),d.species?SPECIES.find((x)=>x.name===d.species)?.grants??[]:[]),
  mk("background","background","배경","배경은 클래스와 분리된 Character source입니다.",st(true,false,!!d.background),true,["rules"],choose(BACKGROUNDS,d.background),d.background?BACKGROUNDS.find((x)=>x.name===d.background)?.grants??[]:[]),
  mk("class","class","클래스","현재 시작 레벨의 클래스만 선택합니다. 미래 서브클래스는 레벨업에서 선택합니다.",st(true,false,!!d.className),true,["rules"],choose(CLASSES,d.className),d.className?CLASSES.find((x)=>x.name===d.className)?.grants??[]:[]),
  mk("abilities","abilities","능력치","RulesProfile 방식으로 능력치를 생성합니다.",st(true,!d.className,!abilityBlock),true,["class"],[],[],/배열|Roll Slot|포인트 구매|커스텀/),
  mk("proficiencies","proficiencies","숙련 · 언어 · 도구","자동 숙련은 확인하고 실제 선택만 처리합니다.",st(true,!d.className,d.selectedSkills.length===2,d.selectedSkills.some((x)=>!m.skills.includes(x))),true,["class","background"],m.skills.map((x)=>({...opt(`skill.${x}`,x,x,"기술 숙련 Choice",["기술 숙련"]),selected:d.selectedSkills.includes(x)})),[`${m.saves.join(" · ")} 내성`],/기술/),
  mk("class-choices","class-choices","클래스 초기 선택","현재 레벨에 열린 ChoiceDefinition만 표시합니다.",fighter.length?st(true,!d.className,(d.selectedClassChoices?.length??0)===1):"not-applicable",fighter.length>0,["class"],choose(fighter,d.selectedClassChoices),m.features,/전투 방식/),
  mk("equipment","equipment","장비","시작 장비와 ItemInstance 결과를 별도 선택합니다.",st(true,!d.className,!!d.equipmentPreset),true,["class"],m.gear.map((g,i)=>({...opt(g.id,g.label,g.id,"시작 장비 구성",["시작 ItemInstances","파생값 재계산"],[],i===0),selected:d.equipmentPreset===g.id}))),
  mk("spells","spells","주문 · 기타 선택","source graph가 주문 Choice를 만들 때만 활성화됩니다.",spells.length?st(true,!d.className,d.selectedSpells.length===2):"not-applicable",spells.length>0,["class"],choose(spells,d.selectedSpells),spells.length?["클래스 주문 시전 RuleSource"]:[],/주문 선택/),
  mk("review","review","검토","Source, grants, 파생값, validation, provenance를 검토합니다.",v.some((x)=>x.severity==="blocking")?"incomplete":"complete",true,["identity","species","background","class","abilities","proficiencies","equipment"],[],[],/.*/)
 ];
 const recommended=sections.find((x)=>x.status==="incomplete")?.id??"review";
 return{draftId:d.id,rulesProfileId:d.rulesProfileId,activeSectionId:sections.some((x)=>x.id===d.activeSectionId)?d.activeSectionId!:recommended,recommendedSectionId:recommended,sections,summary:{name:d.name,species:d.species,background:d.background,className:d.className,subclassName:d.subclassName||undefined,level:d.level,abilities:structuredClone(d.abilities),unresolvedCount:sections.filter((x)=>["incomplete","blocked"].includes(x.status)).length,blockingCount:v.filter((x)=>x.severity==="blocking").length,warningCount:v.filter((x)=>x.severity==="warning").length},validation:v};
}
export function recommended(d:CharacterCreateDraft){const [a,b]=meta(d).rec,rest=(Object.keys(d.abilities)as AbilityKey[]).filter((x)=>x!==a&&x!==b),vals=[15,14,13,12,10,8];return Object.fromEntries([a,b,...rest].map((k,i)=>[k,vals[i]]))as CharacterCreateDraft["abilities"];}
