import type { CharacterCreationOptionVm } from "./contracts";
export type Option=Omit<CharacterCreationOptionVm,"selected">;
export const opt=(id:string,name:string,nameEn:string,summary:string,grants:string[],choices:string[]=[],recommended=false):Option=>({id,name,nameEn,summary,source:"SRD 5.2.1",recommended,grants,choices});
export const SPECIES=[opt("species.human","인간","Human","다재다능한 종족",["이동 30 ft","중형","종족 특성"]),opt("species.elf","엘프","Elf","예리한 감각과 요정 혈통",["이동 30 ft","암시야","요정 혈통"]),opt("species.dwarf","드워프","Dwarf","강인한 체질",["암시야","드워프 특성"]),opt("species.halfling","하플링","Halfling","작고 민첩한 종족",["소형","하플링 특성"])];
export const BACKGROUNDS=[opt("background.soldier","병사","Soldier","군사 경험을 가진 배경",["운동 숙련","위협 숙련","배경 장비"]),opt("background.sage","현자","Sage","연구와 학문에 익숙한 배경",["비전 숙련","역사 숙련","배경 장비"]),opt("background.criminal","범죄자","Criminal","은밀한 활동에 익숙한 배경",["은신 숙련","손재주 숙련","배경 장비"]),opt("background.entertainer","연예인","Entertainer","공연과 사교에 익숙한 배경",["곡예 숙련","공연 숙련","배경 장비"])];
export const CLASSES=[opt("class.fighter","전사","Fighter","무기와 방어구를 폭넓게 다루는 전투 클래스",["Hit Die d10","근력·건강 내성","세컨드 윈드"],["전투 방식 1개"]),opt("class.bard","음유시인","Bard","기술과 마법을 함께 사용하는 지원 클래스",["Hit Die d8","민첩·매력 내성","바드 주문 시전"],["기술 숙련","현재 레벨 주문 선택"]),opt("class.wizard","마법사","Wizard","주문서로 비전 마법을 연구하는 클래스",["Hit Die d6","지능·지혜 내성","마법사 주문 시전"],["캔트립/주문 선택"]),opt("class.cleric","성직자","Cleric","신성 마법과 방어 능력을 가진 클래스",["Hit Die d8","지혜·매력 내성","성직자 주문 시전"],["현재 레벨 주문 선택"])];
export const FIGHTER=[opt("choice.fighting-style.defense","전투 방식: 방어","Defense","방어구를 입은 동안 방어 능력을 강화합니다.",["전투 방식 RuleSource"],[],true),opt("choice.fighting-style.archery","전투 방식: 궁술","Archery","원거리 무기에 특화된 선택입니다.",["전투 방식 RuleSource"]),opt("choice.fighting-style.dueling","전투 방식: 결투","Dueling","한 손 무기에 특화된 선택입니다.",["전투 방식 RuleSource"])];
export const SPELLS:Record<string,Option[]>={
"class.bard":[opt("spell.healing-word","치유의 단어","Healing Word","원거리 회복 주문",["Spell RuleSource","Action"],[],true),opt("spell.vicious-mockery","신랄한 조롱","Vicious Mockery","지혜 내성 정신 공격",["Spell RuleSource","Action"],[],true),opt("spell.thunderwave","천둥파","Thunderwave","범위 천둥 주문",["Spell RuleSource","Action"])],
"class.wizard":[opt("spell.magic-missile","마법 미사일","Magic Missile","자동 명중 역장 주문",["Spell RuleSource","Action"],[],true),opt("spell.shield","방패","Shield","공격에 반응하는 방어 주문",["Spell RuleSource","Reaction"],[],true),opt("spell.thunderwave","천둥파","Thunderwave","범위 천둥 주문",["Spell RuleSource","Action"])],
"class.cleric":[opt("spell.healing-word","치유의 단어","Healing Word","원거리 회복 주문",["Spell RuleSource","Action"],[],true),opt("spell.guiding-bolt","인도하는 화살","Guiding Bolt","빛나는 원거리 주문 공격",["Spell RuleSource","Action"],[],true),opt("spell.sacred-flame","신성한 불꽃","Sacred Flame","민첩 내성 신성 공격",["Spell RuleSource","Action"]) ]};
