import type { ActionVm, ActivityEntry, AppRole, AppSnapshot, CharacterSheet, CombatantDefinitionVm, ResolutionView, SceneEntity, SceneVm, SessionMode } from "./contracts";
import { MockAdapter } from "./mockAdapter";
import { applyResolutionEvents } from "./realEventApplyService";
import { projectResolutionEventsToActivity } from "./realActivityProjectionService";
import { resolveRuntimeTargetingFact } from "./realRuntimeAttackFactProvider";
import { resolveRuntimeSaveModifier } from "./realRuntimeStatProvider";
import { recordRuntimeResolutionEvents } from "./runtimeResolutionEventHistory";
import { projectTurnRuntimeToScene } from "./realTurnRuntimeService";
import { commitAdapterTurnRuntimeState, ensureAdapterTurnRuntimeState, snapshotAdapterTurnRuntimeState, turnRuntimeSessions } from "./turnRuntimeSessionRegistry";
import { persistCharacterResolutionEvents } from "./resolutionCharacterWriteBackPort";
import { projectedCharacterById } from "./characterSessionProjectionRegistry";
import { SIMPLEVTT_APP_RULES_PROFILE } from "./realResolutionService";
import { PALADIN_CHANNEL_DIVINITY_RESOURCE_ID, PALADIN_ID } from "../domain/coreClassResources";
import { resolveAbjureFoes } from "../domain/paladinAbjureFoes";

const ACTION_ID="action.paladin.abjure-foes";
type DicePrototype={d20(actionId:string,index?:number):number};
interface AdapterState {role:AppRole;sessionMode:SessionMode;scene:SceneVm;activeCharacter:CharacterSheet;combatantDefinitions:CombatantDefinitionVm[];resolution:ResolutionView|null;activity:ActivityEntry[];lastResolutionId:string|null;lastBefore:unknown;syncChar():void;getSnapshot():Promise<AppSnapshot>}
const previousResolveAction=MockAdapter.prototype.resolveAction;
function actorAction(scene:SceneVm):ActionVm|undefined {for(const actorId of [scene.selectedActorId,scene.currentActorId,...Object.keys(scene.actionsByActor)]){const found=scene.actionsByActor[actorId]?.find((entry)=>entry.id===ACTION_ID);if(found)return found;}}
function relation(actor:SceneEntity,target:SceneEntity){return actor.id===target.id?"self" as const:actor.side===target.side?"ally" as const:"enemy" as const;}
function seedResource(adapter:MockAdapter,internal:AdapterState){let state=snapshotAdapterTurnRuntimeState(adapter,internal.scene);if(!state){ensureAdapterTurnRuntimeState(adapter,internal.scene);state=snapshotAdapterTurnRuntimeState(adapter,internal.scene);}const combatant=state?.combatants[internal.activeCharacter.id];const resource=internal.activeCharacter.resources.find((entry)=>entry.id===PALADIN_CHANNEL_DIVINITY_RESOURCE_ID);if(!state||!combatant||!resource||combatant.resources.some((entry)=>entry.id===resource.id))return state;combatant.resources.push({id:resource.id,label:resource.label,current:resource.current,maximum:resource.max,recovery:resource.recovery?structuredClone(resource.recovery):undefined});const expected=state.revision;state.revision+=1;return commitAdapterTurnRuntimeState(adapter,internal.scene,expected,state)?snapshotAdapterTurnRuntimeState(adapter,internal.scene):undefined;}

MockAdapter.prototype.resolveAction=async function resolvePaladinAbjureFoes(actionId:string,targetIds:string[]){
  if(actionId!==ACTION_ID)return previousResolveAction.call(this,actionId,targetIds);const internal=this as unknown as AdapterState;const snapshot=await internal.getSnapshot();const action=actorAction(snapshot.scene);const actor=action&&internal.scene.entities.find((entry)=>entry.id===action.actorId);
  if(!action?.available||!actor||!targetIds.length||targetIds.length>(action.maxTargets??1)||targetIds.some((id)=>!action.eligibleTargetIds.includes(id)))return snapshot;if(internal.sessionMode==="initiative"&&internal.role==="player"&&action.actorId!==internal.scene.currentActorId)return snapshot;
  const paladinLevel=internal.activeCharacter.classLevels?.find((entry)=>entry.classId===PALADIN_ID)?.level??0;const state=seedResource(this,internal);if(!state||paladinLevel<9)return snapshot;const resolutionId=`paladin.abjure-foes.${Date.now()}.${Math.floor(Math.random()*1000)}`;
  const targets=[];for(const [index,id] of targetIds.entries()){const entity=internal.scene.entities.find((entry)=>entry.id===id);if(!entity||!state.combatants[id])return snapshot;const sheet=entity.id===internal.activeCharacter.id?internal.activeCharacter:projectedCharacterById(this,entity.id)?.sheet;let save;try{save=resolveRuntimeSaveModifier(entity,sheet??internal.activeCharacter,"wis",internal.combatantDefinitions);}catch{return snapshot;}const spatial=resolveRuntimeTargetingFact(internal.scene,action.actorId,id);targets.push({id,kind:"creature" as const,relation:relation(actor,entity),distanceFeet:spatial.distanceFeet,visible:spatial.visible,cover:spatial.cover,wisdomSaveModifier:save.modifier,saveDice:{id:`${resolutionId}:save:${index}`,purpose:"Abjure Foes Wisdom save",sides:20 as const,faces:[(MockAdapter.prototype as unknown as DicePrototype).d20.call(this,actionId,index)]}});}
  const charisma=Math.floor((internal.activeCharacter.abilities.cha-10)/2);const committed=resolveAbjureFoes(SIMPLEVTT_APP_RULES_PROFILE,state,{id:resolutionId,actorId:action.actorId,expectedRevision:state.revision,paladinLevel,charismaModifier:charisma,spellSaveDc:action.saveDc??8,targets,channelDivinityResourceId:PALADIN_CHANNEL_DIVINITY_RESOURCE_ID,useActionEconomy:internal.sessionMode==="initiative"});if(committed.status==="rejected")return snapshot;
  const projected=applyResolutionEvents(internal.scene,committed.events,internal.activeCharacter.resources,internal.activeCharacter.items,state);if(projected.status==="rejected")return snapshot;const writeBack=await persistCharacterResolutionEvents(this,committed.events,"forward");if(writeBack.status==="rejected")return snapshot;if(!commitAdapterTurnRuntimeState(this,internal.scene,state.revision,committed.state)){if(writeBack.changed)await persistCharacterResolutionEvents(this,committed.events,"inverse");return snapshot;}
  internal.scene=projected.scene;internal.activeCharacter.resources=projected.resources;const session=turnRuntimeSessions.get(this);if(session)projectTurnRuntimeToScene(session,internal.scene);const names=targetIds.map((id)=>internal.scene.entities.find((entry)=>entry.id===id)?.name??id);const affected=targetIds.filter((id)=>committed.state.effects.some((effect)=>effect.targetId===id&&effect.sourceId==="feature:paladin.channel-divinity.abjure-foes")).length;const outcome=`${targetIds.length}명 판정 · ${affected}명 공포`;
  const resolution:ResolutionView={id:resolutionId,actorId:action.actorId,targetIds,actionId:ACTION_ID,actionName:"적 질책",rollKind:"save",stage:"complete",authoritativeDice:targets.flatMap((target)=>target.saveDice.faces),saveResults:[],damageComponents:[],compact:outcome,detail:["실패한 대상은 피해를 받기 전까지 1분간 공포 상태입니다."],provenance:["SRD 5.2.1 · Paladin Abjure Foes"],calculatedOutcome:outcome,finalOutcome:outcome,stateChanges:projected.stateChanges,adjudicated:false,canAdvance:false};internal.resolution=resolution;internal.activity.unshift(projectResolutionEventsToActivity({resolution,events:committed.events,actorName:actor.name,targetNames:names}));internal.lastResolutionId=resolutionId;internal.lastBefore=null;recordRuntimeResolutionEvents(this,resolutionId,committed.events);internal.syncChar();return internal.getSnapshot();
};
