const SPELL_NAMES_KO: Record<string, string> = {
  "dnd.srd521.spell.acid-splash":"산성 거품",
  "dnd.srd521.spell.alarm":"경보",
  "dnd.srd521.spell.animal-friendship":"동물 친밀화",
  "dnd.srd521.spell.bane":"억압",
  "dnd.srd521.spell.bless":"축복",
  "dnd.srd521.spell.burning-hands":"타오르는 손길",
  "dnd.srd521.spell.charm-person":"인간형 매혹",
  "dnd.srd521.spell.chill-touch":"냉랭한 접촉",
  "dnd.srd521.spell.chromatic-orb":"색채 보주",
  "dnd.srd521.spell.color-spray":"색 분사",
  "dnd.srd521.spell.command":"명령",
  "dnd.srd521.spell.comprehend-languages":"언어 이해",
  "dnd.srd521.spell.create-or-destroy-water":"물 창조 또는 파괴",
  "dnd.srd521.spell.cure-wounds":"상처 치료",
  "dnd.srd521.spell.dancing-lights":"춤추는 빛",
  "dnd.srd521.spell.detect-evil-and-good":"악과 선 탐지",
  "dnd.srd521.spell.detect-magic":"마법 탐지",
  "dnd.srd521.spell.detect-poison-and-disease":"독과 질병 탐지",
  "dnd.srd521.spell.disguise-self":"자기 위장",
  "dnd.srd521.spell.dissonant-whispers":"불협화음의 속삭임",
  "dnd.srd521.spell.divine-favor":"신성한 청원",
  "dnd.srd521.spell.divine-smite":"신성한 강타",
  "dnd.srd521.spell.druidcraft":"드루이드술",
  "dnd.srd521.spell.eldritch-blast":"섬뜩한 방출",
  "dnd.srd521.spell.elementalism":"원소술",
  "dnd.srd521.spell.ensnaring-strike":"휘감는 일격",
  "dnd.srd521.spell.entangle":"옭아매기",
  "dnd.srd521.spell.expeditious-retreat":"신속한 후퇴",
  "dnd.srd521.spell.faerie-fire":"요정 불꽃",
  "dnd.srd521.spell.false-life":"거짓된 생명",
  "dnd.srd521.spell.feather-fall":"깃털 낙하",
  "dnd.srd521.spell.find-familiar":"패밀리어 찾기",
  "dnd.srd521.spell.fire-bolt":"화염 화살",
  "dnd.srd521.spell.floating-disk":"부유 원반",
  "dnd.srd521.spell.fog-cloud":"안개 구름",
  "dnd.srd521.spell.goodberry":"굿베리",
  "dnd.srd521.spell.grease":"기름칠",
  "dnd.srd521.spell.guidance":"인도",
  "dnd.srd521.spell.guiding-bolt":"유도 화살",
  "dnd.srd521.spell.healing-word":"치유의 단어",
  "dnd.srd521.spell.hellish-rebuke":"지옥의 책망",
  "dnd.srd521.spell.heroism":"영웅심",
  "dnd.srd521.spell.hex":"사술",
  "dnd.srd521.spell.hideous-laughter":"끔찍한 웃음",
  "dnd.srd521.spell.hunter-s-mark":"사냥꾼의 표식",
  "dnd.srd521.spell.ice-knife":"얼음 칼",
  "dnd.srd521.spell.identify":"식별",
  "dnd.srd521.spell.illusory-script":"환영 문서",
  "dnd.srd521.spell.inflict-wounds":"상처 가해",
  "dnd.srd521.spell.jump":"도약",
  "dnd.srd521.spell.light":"빛",
  "dnd.srd521.spell.longstrider":"활보",
  "dnd.srd521.spell.mage-armor":"마법 갑주",
  "dnd.srd521.spell.mage-hand":"마법사의 손",
  "dnd.srd521.spell.magic-missile":"마법 화살",
  "dnd.srd521.spell.mending":"수리",
  "dnd.srd521.spell.message":"전달",
  "dnd.srd521.spell.minor-illusion":"하급 환영",
  "dnd.srd521.spell.poison-spray":"독 분사",
  "dnd.srd521.spell.prestidigitation":"요술",
  "dnd.srd521.spell.produce-flame":"화염 생성",
  "dnd.srd521.spell.protection-from-evil-and-good":"악과 선으로부터의 보호",
  "dnd.srd521.spell.purify-food-and-drink":"음식과 물 정화",
  "dnd.srd521.spell.ray-of-frost":"서리 광선",
  "dnd.srd521.spell.ray-of-sickness":"질병 광선",
  "dnd.srd521.spell.resistance":"저항",
  "dnd.srd521.spell.sacred-flame":"신성한 불길",
  "dnd.srd521.spell.sanctuary":"성역",
  "dnd.srd521.spell.searing-smite":"작열하는 강타",
  "dnd.srd521.spell.shield":"방패",
  "dnd.srd521.spell.shield-of-faith":"신앙의 방패",
  "dnd.srd521.spell.shillelagh":"마력 곤봉",
  "dnd.srd521.spell.shocking-grasp":"전격의 손아귀",
  "dnd.srd521.spell.silent-image":"조용한 영상",
  "dnd.srd521.spell.sleep":"수면",
  "dnd.srd521.spell.sorcerous-burst":"소서러의 폭발",
  "dnd.srd521.spell.spare-the-dying":"빈사 안정",
  "dnd.srd521.spell.speak-with-animals":"동물과의 대화",
  "dnd.srd521.spell.starry-wisp":"별빛 도깨비불",
  "dnd.srd521.spell.thaumaturgy":"단순마술",
  "dnd.srd521.spell.thunderwave":"천둥파동",
  "dnd.srd521.spell.true-strike":"참된 일격",
  "dnd.srd521.spell.unseen-servant":"보이지 않는 하인",
  "dnd.srd521.spell.vicious-mockery":"잔혹한 모욕",
};

const GENERIC_SUMMARIES = new Set(["SRD 소마법", "SRD 1레벨 주문"]);

export function spellNameKo(id: string, fallback?: string) {
  return SPELL_NAMES_KO[id] ?? fallback ?? id;
}

export function hasLocalizedSpellName(id: string) {
  return Boolean(SPELL_NAMES_KO[id]);
}

export function isGenericSpellSummary(summary?: string) {
  return Boolean(summary && GENERIC_SUMMARIES.has(summary));
}

export const SPELL_DESCRIPTION_PENDING = "상세 SRD 주문 설명은 아직 presentation catalog에 연결되지 않았습니다. 현재 표시되는 주문 레벨과 출처는 설명 본문이 아닙니다.";
