import { useEffect, useState } from "react";
import { useSimpleVtt } from "./app/AppProvider";
import type { AbilityKey, CatalogEntry, CharacterCreateDraft, CharacterCreationPlan, CharacterCreationSection, CharacterCreationSectionStatus, LevelUpCommand, LevelUpDraft } from "./app/contracts";
import { AbilitiesSection } from "./character-create/V09Abilities";
import { ClassChoicesSection, ClassSection, EquipmentSection, IdentitySection, ProficienciesSection, ReviewSection, SourceSection, SpellSection } from "./character-create/V09Sections";

const LABELS: Record<string, string> = { identity: "정체성", species: "종족", class: "클래스", background: "배경", abilities: "능력치", proficiencies: "기술", review: "검토" };
const PRIMARY_IDS = ["identity", "species", "class", "background", "abilities", "proficiencies", "review"] as const;
const CONTEXT_IDS = ["class-choices", "equipment", "spells"] as const;
const ABILITY_LABELS: Record<AbilityKey, string> = { str: "근력", dex: "민첩", con: "건강", int: "지능", wis: "지혜", cha: "매력" };
const ABILITY_KEYS = Object.keys(ABILITY_LABELS) as AbilityKey[];

type LevelFocus = "hp" | "choice" | "review";

function primarySections(plan: CharacterCreationPlan) {
  const result: CharacterCreationSection[] = [];
  for (const id of PRIMARY_IDS) { const section = plan.sections.find((item) => item.id === id); if (section) result.push(section); }
  return result;
}
function contextSections(plan: CharacterCreationPlan, primaryId: string) {
  const result: CharacterCreationSection[] = [];
  if (primaryId !== "class") return result;
  for (const id of CONTEXT_IDS) { const section = plan.sections.find((item) => item.id === id); if (section && section.status !== "not-applicable") result.push(section); }
  return result;
}
function primaryStatus(plan: CharacterCreationPlan, section: CharacterCreationSection): CharacterCreationSectionStatus {
  if (section.id !== "class") return section.status;
  const children = contextSections(plan, "class");
  if (children.some((item) => item.status === "blocked")) return "blocked";
  if (children.some((item) => item.status === "incomplete")) return "incomplete";
  if (children.some((item) => item.status === "warning")) return "warning";
  return section.status;
}
function nextPrimary(plan: CharacterCreationPlan, current: string, direction: 1 | -1) {
  const items = primarySections(plan); const index = Math.max(0, items.findIndex((item) => item.id === current));
  return items[Math.min(items.length - 1, Math.max(0, index + direction))]?.id ?? "identity";
}

const FOCUSED_STYLE = `
.focused-create-shell,.focused-level-shell{height:100%;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:radial-gradient(circle at 45% 8%,var(--accent-soft),transparent 30rem),var(--bg)}
.focused-create-header{min-height:76px;display:grid;grid-template-columns:190px minmax(520px,1fr) 145px;border-bottom:1px solid var(--line);background:var(--surface)}
.focused-create-title{padding:14px 18px;display:grid;align-content:center;gap:4px;min-width:0}.focused-create-title span,.focused-level-header span,.focused-level-nav>span,.focused-level-panel>span,.focused-level-auto>span,.focused-import>span{color:var(--accent);font-size:8px;font-weight:900;letter-spacing:.1em}.focused-create-title strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:700 17px Georgia,"Noto Serif KR",serif}
.focused-create-tabs{display:grid;grid-template-columns:repeat(7,minmax(68px,1fr))}.focused-create-tabs button{position:relative;border:0;border-left:1px solid var(--line);border-radius:0;background:transparent;color:var(--muted);display:grid;place-items:center;align-content:center;gap:4px}.focused-create-tabs button:hover,.focused-create-tabs button.active{background:var(--accent-soft);color:var(--text)}.focused-create-tabs button.active:after{content:"";position:absolute;left:18%;right:18%;bottom:0;height:2px;background:var(--accent)}.focused-create-tabs i{height:11px;color:var(--quiet);font-style:normal}.focused-create-tabs .status-complete i{color:var(--good)}.focused-create-tabs .status-incomplete i,.focused-create-tabs .status-warning i,.focused-create-tabs .status-blocked i{color:var(--accent)}.focused-create-tabs span{font-size:9px;font-weight:900;white-space:nowrap}.focused-create-header-actions{padding:12px;display:flex;align-items:center;justify-content:flex-end;gap:6px;border-left:1px solid var(--line)}
.focused-create-body{min-height:0;display:grid;grid-template-columns:minmax(0,1fr) 300px}.focused-create-stage{min-width:0;min-height:0;overflow:auto}.focused-create-stage>.create-v09-section,.focused-class-flow>.create-v09-section{max-width:1050px;padding-top:34px}.focused-context-block{max-width:1050px;margin:-30px auto 38px;padding:0 32px 28px}.focused-context-heading{margin:8px 0;padding:13px 15px;border-left:2px solid var(--accent);background:var(--accent-soft)}.focused-context-heading span{color:var(--accent);font-size:8px;font-weight:900}.focused-context-heading strong{display:block;margin-top:4px;font:700 17px Georgia,"Noto Serif KR",serif}.focused-context-heading p{margin:5px 0 0;color:var(--muted);font-size:9px}.focused-context-block>.create-v09-section{max-width:none;padding:16px 0 0}.focused-context-block>.create-v09-section>header{padding-bottom:10px}.focused-context-block>.create-v09-section>header h2{font-size:18px}
.focused-character-preview{min-height:0;overflow:auto;padding:22px 20px;border-left:1px solid var(--line);background:var(--surface)}.focused-character-portrait{height:160px;margin:-22px -20px 18px;display:grid;place-items:center;border-bottom:1px solid var(--line);background:radial-gradient(circle,var(--accent-soft),transparent 65%),var(--recess)}.focused-character-portrait span{width:80px;height:80px;display:grid;place-items:center;border:1px solid var(--line-strong);border-radius:50%;color:var(--accent);font:700 34px Georgia,serif}.focused-character-identity h2{margin:0 0 4px;font-size:24px}.focused-character-identity p{margin:0;color:var(--accent);font-weight:800}.focused-character-identity>span{display:block;margin-top:4px;color:var(--muted);font-size:9px}.focused-character-vitals{margin-top:16px;display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.focused-character-vitals>div,.focused-character-abilities>div{display:grid;place-items:center;background:var(--recess);border:1px solid var(--line)}.focused-character-vitals>div{padding:9px 4px}.focused-character-vitals span,.focused-character-abilities span{color:var(--quiet);font-size:8px}.focused-character-vitals strong{font-size:18px}.focused-character-abilities{margin-top:6px;display:grid;grid-template-columns:repeat(6,1fr);gap:2px}.focused-character-abilities>div{padding:6px 1px}.focused-review-button{width:100%;margin-top:16px;padding:11px;display:grid;gap:3px;text-align:left;border-color:var(--line-strong);background:var(--accent-soft)}.focused-review-button span{color:var(--accent);font-size:9px;font-weight:900}.focused-review-button strong{font-size:9px}.focused-create-footer{min-height:64px;padding:9px 16px;display:grid;grid-template-columns:110px 1fr 150px;align-items:center;gap:12px;border-top:1px solid var(--line);background:var(--surface)}.focused-create-footer>div{min-width:0;display:grid;justify-items:center;gap:3px}.focused-create-footer>div small{max-width:650px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted);font-size:8px}.focused-create-empty{height:100%;display:grid;place-items:center;text-align:center}.focused-create-empty>div{max-width:520px;display:grid;gap:11px}.focused-import{max-width:860px;margin:0 auto;padding:40px 32px}.focused-import textarea{width:100%;min-height:300px;margin:16px 0 10px}
.focused-level-header{min-height:80px;padding:13px 20px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);background:var(--surface)}.focused-level-header h1{margin:4px 0 0;font-size:23px}.focused-level-body{min-height:0;display:grid;grid-template-columns:220px minmax(0,1fr) 300px}.focused-level-nav{padding:18px 9px;border-right:1px solid var(--line);background:var(--surface)}.focused-level-nav>span{display:block;padding:0 7px 9px}.focused-level-nav button{width:100%;margin-bottom:5px;padding:10px 9px;display:grid;grid-template-columns:22px 1fr;gap:7px;text-align:left;background:transparent;border-color:transparent}.focused-level-nav button.active{background:var(--accent-soft);border-color:var(--line-strong)}.focused-level-nav button i{width:21px;height:21px;display:grid;place-items:center;border:1px solid var(--line);border-radius:50%;color:var(--accent);font-style:normal}.focused-level-nav button strong,.focused-level-nav button small{display:block}.focused-level-nav button strong{font-size:9px}.focused-level-nav button small{margin-top:3px;color:var(--quiet);font-size:8px}.focused-level-stage{min-width:0;min-height:0;overflow:auto;padding:30px}.focused-level-stage-inner{max-width:860px;margin:0 auto}.focused-level-auto{margin-bottom:17px;padding:13px;border:1px solid color-mix(in srgb,var(--good) 28%,var(--line));background:color-mix(in srgb,var(--good) 5%,var(--surface))}.focused-level-auto>span{color:var(--good)}.focused-level-auto h2{margin:5px 0 9px;font-size:19px}.focused-level-auto p{margin:4px 0;color:var(--muted);font-size:9px}.focused-level-panel h2{margin:6px 0;font-size:27px}.focused-level-panel>p{margin:0 0 17px;color:var(--muted)}.focused-level-preview{min-height:0;overflow:auto;padding:20px;border-left:1px solid var(--line);background:var(--surface)}.focused-level-preview h2{margin:6px 0 15px}.focused-level-footer{min-height:64px;padding:9px 16px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);background:var(--surface)}.focused-level-footer>span{color:var(--muted);font-size:9px}
@media(max-width:930px){.focused-create-header{grid-template-columns:1fr auto}.focused-create-tabs{grid-column:1/-1;grid-row:2}.focused-create-body{grid-template-columns:1fr}.focused-character-preview{display:none}.focused-level-body{grid-template-columns:155px 1fr}.focused-level-preview{display:none}}
`;

export function CharacterCreateScreenV09({ onDone, onCancel }: { onDone(): void; onCancel(): void }) {
  const { snapshot, createCharacterDraft, updateCharacterDraft, finalizeCharacterDraft } = useSimpleVtt();
  const [importText, setImportText] = useState('{\n  "name": "새 캐릭터",\n  "className": "전사",\n  "species": "인간",\n  "background": "병사",\n  "level": 1\n}');
  if (!snapshot?.createDraft) return <div className="focused-create-empty"><style>{FOCUSED_STYLE}</style><div><span>CHARACTER CREATION</span><h1>새 캐릭터</h1><p>큰 선택을 정하고 필요한 선택은 그 자리에서 이어서 처리합니다.</p><button className="primary" onClick={() => createCharacterDraft("guided")}>캐릭터 만들기</button><button onClick={onCancel}>돌아가기</button></div></div>;
  const draft = snapshot.createDraft; const plan = snapshot.creationPlan;
  if (!plan) return <div className="loading-screen">캐릭터 선택 준비 중…</div>;
  const primary = primarySections(plan);
  const activeId = primary.some((section) => section.id === plan.activeSectionId) ? plan.activeSectionId : CONTEXT_IDS.includes(plan.activeSectionId as (typeof CONTEXT_IDS)[number]) ? "class" : plan.recommendedSectionId;
  const active = primary.find((section) => section.id === activeId) ?? primary[0]; const context = contextSections(plan, active.id);
  const blocking = plan.validation.some((message) => message.severity === "blocking"); const importPending = draft.mode === "import" && draft.importStatus !== "valid";
  const go = (id: string) => void updateCharacterDraft({ type: "set-section", value: id });
  return <div className="focused-create-shell"><style>{FOCUSED_STYLE}</style>
    <header className="focused-create-header"><div className="focused-create-title"><span>{draft.editingCharacterId ? "CHARACTER EDIT" : "CHARACTER CREATION"}</span><strong>{draft.name || "이름 없는 캐릭터"}</strong></div><nav className="focused-create-tabs">{primary.map((section) => { const status = primaryStatus(plan, section); return <button key={section.id} className={`${active.id === section.id ? "active" : ""} status-${status}`} onClick={() => go(section.id)}><i>{status === "complete" ? "✓" : status === "warning" ? "!" : status === "incomplete" || status === "blocked" ? "•" : ""}</i><span>{LABELS[section.id] ?? section.label}</span></button>; })}</nav><div className="focused-create-header-actions"><button onClick={() => createCharacterDraft("import")}>JSON</button><button onClick={onCancel}>닫기</button></div></header>
    <div className="focused-create-body"><main className="focused-create-stage">{importPending ? <ImportPanel draft={draft} value={importText} setValue={setImportText} onPreview={() => updateCharacterDraft({ type: "import-json", value: importText })}/> : <PrimarySection section={active} context={context} plan={plan} draft={draft}/>}</main><CharacterPreview plan={plan} draft={draft} onReview={() => go("review")}/></div>
    <footer className="focused-create-footer"><button disabled={primary[0]?.id === active.id || importPending} onClick={() => go(nextPrimary(plan, active.id, -1))}>이전</button><div><span>{LABELS[active.id] ?? active.label}</span><small>{active.id === "class" && context.length ? `${draft.className || "클래스"}에 필요한 선택을 여기서 함께 처리합니다.` : active.description}</small></div>{active.id === "review" ? <button className="primary" disabled={blocking || importPending} onClick={async () => { await finalizeCharacterDraft(); onDone(); }}>{draft.editingCharacterId ? "변경 적용" : "모험 시작"}</button> : <button className="primary" disabled={importPending} onClick={() => go(nextPrimary(plan, active.id, 1))}>다음</button>}</footer>
  </div>;
}

function PrimarySection({ section, context, plan, draft }: { section: CharacterCreationSection; context: CharacterCreationSection[]; plan: CharacterCreationPlan; draft: CharacterCreateDraft }) {
  if (section.kind === "identity") return <IdentitySection section={section} draft={draft}/>;
  if (section.kind === "species") return <SourceSection section={section} commandType="set-species"/>;
  if (section.kind === "background") return <SourceSection section={section} commandType="set-background"/>;
  if (section.kind === "class") return <div className="focused-class-flow"><ClassSection section={section} draft={draft}/>{draft.className && context.length > 0 && <div className="focused-context-block"><div className="focused-context-heading"><span>현재 클래스 선택</span><strong>{draft.className}에게 지금 필요한 결정</strong><p>별도 단계로 이동하지 않고 클래스 선택의 결과를 바로 이어서 정합니다.</p></div>{context.map((child) => <ContextSection key={child.id} section={child} draft={draft}/>)}</div>}</div>;
  if (section.kind === "abilities") return <AbilitiesSection section={section} draft={draft}/>;
  if (section.kind === "proficiencies") return <ProficienciesSection section={section} draft={draft}/>;
  return <ReviewSection section={section} plan={plan} draft={draft}/>;
}
function ContextSection({ section, draft }: { section: CharacterCreationSection; draft: CharacterCreateDraft }) { if (section.kind === "class-choices") return <ClassChoicesSection section={section}/>; if (section.kind === "equipment") return <EquipmentSection section={section}/>; if (section.kind === "spells") return <SpellSection section={section} draft={draft}/>; return null; }
function CharacterPreview({ plan, draft, onReview }: { plan: CharacterCreationPlan; draft: CharacterCreateDraft; onReview(): void }) { const unresolved = primarySections(plan).filter((section) => ["incomplete", "blocked"].includes(primaryStatus(plan, section))).map((section) => LABELS[section.id] ?? section.label); return <aside className="focused-character-preview"><div className="focused-character-portrait"><span>{(draft.name || "?").slice(0, 1)}</span></div><div className="focused-character-identity"><h2>{draft.name || "이름 없음"}</h2><p>{draft.className ? `${draft.className} ${draft.level}` : "클래스 미선택"}</p><span>{draft.species || "종족 미선택"} · {draft.background || "배경 미선택"}</span></div><div className="focused-character-vitals"><div><span>HP</span><strong>{draft.derived.hp}</strong></div><div><span>AC</span><strong>{draft.derived.ac}</strong></div><div><span>이동</span><strong>{draft.derived.speed}</strong></div></div><div className="focused-character-abilities">{Object.entries(draft.abilities).map(([key, value]) => <div key={key}><span>{key.toUpperCase()}</span><strong>{value}</strong></div>)}</div><button className="focused-review-button" onClick={onReview}><span>캐릭터 검토</span><strong>{unresolved.length ? `${unresolved.join(" · ")} 확인 필요` : "준비 완료"}</strong></button></aside>; }
function ImportPanel({ draft, value, setValue, onPreview }: { draft: CharacterCreateDraft; value: string; setValue(value: string): void; onPreview(): void }) { return <section className="focused-import"><span>IMPORT CHARACTER</span><h2>JSON 가져오기</h2><p>가져온 캐릭터도 같은 선택 화면에서 검토합니다.</p><textarea value={value} onChange={(event) => setValue(event.target.value)}/><button className="primary" onClick={onPreview}>가져와서 검토</button>{draft.importStatus && draft.importStatus !== "idle" && <div className={`validation ${draft.importStatus === "valid" ? "info" : "blocking"}`}>{draft.importMessage}</div>}</section>; }

export function LevelUpFocused({ onDone, onCancel }: { onDone(): void; onCancel(): void }) {
  const { snapshot, startLevelUp, updateLevelUp, commitLevelUp } = useSimpleVtt(); const character = snapshot?.activeCharacter; const draft = snapshot?.levelUpDraft; const [focus, setFocus] = useState<LevelFocus>("choice");
  useEffect(() => { if (character && !draft) void startLevelUp(character.id); }, [character, draft, startLevelUp]);
  if (!snapshot || !character || !draft) return <div className="loading-screen">레벨 업 준비 중…</div>;
  const blocking = draft.validation.some((message) => message.severity === "blocking"); const eligibleFeats = snapshot.catalog.filter((entry) => entry.category === "feat");
  const tasks: Array<{ id: LevelFocus; label: string; detail: string }> = [{ id:"hp", label:"생명력", detail:`${draft.preview.maxHpBefore} → ${draft.preview.maxHpAfter}` },{ id:"choice", label:"능력치 또는 재주", detail:draft.asiMode === "feat" ? "재주 선택" : draft.asiMode === "split" ? "+1 / +1" : "+2" },{ id:"review", label:"변경 확인", detail:`${draft.preview.grantedFeatures.length}개 자동 획득` }];
  return <div className="focused-level-shell"><style>{FOCUSED_STYLE}</style><header className="focused-level-header"><div><span>LEVEL UP</span><h1>{character.name} · {draft.fromLevel} → {draft.toLevel}</h1></div><button onClick={onCancel}>취소</button></header><div className="focused-level-body"><aside className="focused-level-nav"><span>이번 레벨에서 결정할 것</span>{tasks.map((item, index) => <button key={item.id} className={focus === item.id ? "active" : ""} onClick={() => setFocus(item.id)}><i>{index + 1}</i><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}</aside><main className="focused-level-stage"><div className="focused-level-stage-inner"><AutomaticLevelChanges draft={draft}/>{focus === "hp" ? <HpChoice draft={draft} onUpdate={updateLevelUp}/> : focus === "choice" ? <AdvancementChoice draft={draft} eligibleFeats={eligibleFeats} onUpdate={updateLevelUp}/> : <LevelReview draft={draft}/>}</div></main><aside className="focused-level-preview"><span>AFTER LEVEL UP</span><h2>{character.name} {draft.toLevel}레벨</h2><div className="diff-list rich">{draft.preview.diffs.map((diff) => <div key={diff.label}><span>{diff.label}<small>{diff.source}</small></span><b>{diff.before}</b><i>→</i><strong>{diff.after}</strong></div>)}</div>{draft.validation.map((message) => <div className={`validation ${message.severity}`} key={message.message}>{message.message}</div>)}</aside></div><footer className="focused-level-footer"><span>자동 획득은 바로 적용되고, 필요한 선택만 확인합니다.</span><button className="primary" disabled={blocking} onClick={async () => { await commitLevelUp(); onDone(); }}>레벨 업 확정</button></footer></div>;
}
function AutomaticLevelChanges({ draft }: { draft: LevelUpDraft }) { return <section className="focused-level-auto"><span>자동 획득</span><h2>{draft.preview.grantedFeatures.join(" · ") || "클래스 진행"}</h2><p>Hit Dice {draft.preview.hitDiceBefore} → {draft.preview.hitDiceAfter}</p>{draft.preview.resourceChanges.map((change) => <p key={change}>{change}</p>)}</section>; }
function HpChoice({ draft, onUpdate }: { draft: LevelUpDraft; onUpdate(command: LevelUpCommand): Promise<void> }) { return <section className="focused-level-panel"><span>HIT POINTS</span><h2>생명력 증가</h2><p>이번 레벨에서 사용할 HP 증가 방식을 선택합니다.</p><div className="method-tabs"><button className={draft.hpMethod === "fixed" ? "active" : ""} onClick={() => onUpdate({ type:"set-hp-method", value:"fixed" })}><strong>고정값</strong><span>최대 HP {draft.preview.maxHpBefore} → {draft.preview.maxHpAfter}</span></button><button className={draft.hpMethod === "roll" ? "active" : ""} onClick={() => onUpdate({ type:"set-hp-method", value:"roll" })}><strong>Hit Die 굴림</strong><span>굴림 결과 사용</span></button></div></section>; }
function AdvancementChoice({ draft, eligibleFeats, onUpdate }: { draft: LevelUpDraft; eligibleFeats: CatalogEntry[]; onUpdate(command: LevelUpCommand): Promise<void> }) { return <section className="focused-level-panel"><span>CHOICE</span><h2>능력치 향상 또는 재주</h2><p>현재 레벨에서 실제로 열린 선택만 처리합니다.</p><div className="method-tabs"><button className={draft.asiMode === "plus-two" ? "active" : ""} onClick={() => onUpdate({ type:"set-asi-mode", value:"plus-two" })}><strong>능력치 +2</strong><span>한 능력치</span></button><button className={draft.asiMode === "split" ? "active" : ""} onClick={() => onUpdate({ type:"set-asi-mode", value:"split" })}><strong>+1 / +1</strong><span>서로 다른 두 능력치</span></button><button className={draft.asiMode === "feat" ? "active" : ""} onClick={() => onUpdate({ type:"set-asi-mode", value:"feat" })}><strong>재주</strong><span>적격 목록에서 선택</span></button></div>{draft.asiMode === "feat" ? <div className="catalog-choice-grid">{eligibleFeats.map((feat) => <button className={draft.featId === feat.id ? "selected" : ""} key={feat.id} onClick={() => onUpdate({ type:"set-feat", value:feat.id })}><strong>{feat.nameKo}</strong><small>{feat.nameEn}</small><span>{feat.source}</span></button>)}</div> : <div className="choice-grid"><label className="field"><span>첫 번째 능력치</span><select value={draft.asiPrimary} onChange={(event) => onUpdate({ type:"set-asi-primary", value:event.target.value })}>{ABILITY_KEYS.map((key) => <option value={key} key={key}>{ABILITY_LABELS[key]}</option>)}</select></label>{draft.asiMode === "split" && <label className="field"><span>두 번째 능력치</span><select value={draft.asiSecondary} onChange={(event) => onUpdate({ type:"set-asi-secondary", value:event.target.value })}>{ABILITY_KEYS.map((key) => <option value={key} key={key}>{ABILITY_LABELS[key]}</option>)}</select></label>}</div>}</section>; }
function LevelReview({ draft }: { draft: LevelUpDraft }) { return <section className="focused-level-panel"><span>REVIEW</span><h2>이번 레벨의 변화</h2><p>자동 획득과 선택 결과를 한 번에 확인합니다.</p><div className="review-rows">{draft.preview.diffs.map((diff) => <div key={diff.label}><span>{diff.label}</span><strong>{diff.before} → {diff.after} · {diff.source}</strong></div>)}</div></section>; }
